### ISSUE TITLE
debian 10 buster nodejs/npm node-gyp dependency breaks install

### ISSUE THREAD

**Issue by jorge-vitrubio** [Mailtrain-org/mailtrain#1063]
Hello, this is to report a broken dependency in debian 10 buster.

```bash
root@locallamp:/opt/mailtrain# bash setup/install-debian10-https.sh  mailtrain.locallampbuster sbox-mailtrain.locallampbuster newsletter.locallampbuster lamp@locallampbuster
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnupg is already the newest version (2.2.12-1+deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
OK
deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main
Hit:1 http://deb.debian.org/debian stable InRelease
Hit:2 https://deb.nodesource.com/node_10.x buster InRelease                                                                  
Hit:3 http://deb.debian.org/debian stable-updates InRelease                                                                  
Hit:4 http://deb.debian.org/debian-security stable/updates InRelease
Ign:5 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 InRelease
Hit:6 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bzip2 is already the newest version (1.0.6-9.2~deb10u1).
imagemagick is already the newest version (8:6.9.10.23+dfsg-2.1+deb10u1).
mariadb-server is already the newest version (1:10.3.27-0+deb10u1).
pwgen is already the newest version (2.08-1).
wget is already the newest version (1.20.1-1.1).
curl is already the newest version (7.64.0-4+deb10u2).
nodejs is already the newest version (10.24.1-1nodesource1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Conflicts: npm
 npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I don't get it because a newer version is available in debian

```bash
root@locallamp:/opt/mailtrain# apt show node-gyp -a
Package: node-gyp
Version: 3.8.0-6
Priority: optional
Section: javascript
Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Installed-Size: 121 kB
Depends: nodejs, libnode-dev, gyp (>= 0.1+20150913git1f374df9), node-glob, node-graceful-fs, node-mkdirp, node-nopt, node-npmlog, node-osenv, node-request, node-rimraf, node-semver, node-tar, node-which
Recommends: build-essential
Homepage: https://github.com/nodejs/node-gyp
Download-Size: 36.9 kB
APT-Sources: http://deb.debian.org/debian stable/main amd64 Packages
Description: Native addon build tool for Node.js
 node-gyp is a cross-platform command-line tool written in Node.js
 for compiling native addon modules for Node.js.
 .
 It features :
  * Easy to use, consistent interface
  * Same commands to build a module on every platform
  * Support of multiple target versions of Node.js
 .
 node-gyp replaces node-waf program which was deprecated in Node.js 0.8
 and removed since Node.js 0.10.
 .
 Node.js is an event-based server-side javascript engine.
```

Currently this is a virsh local machine with debian 10
```bash
root@locallamp:/opt/mailtrain# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by joker-x** [comment]
@jorge-vitrubio can you test https://github.com/podemos-info/mailtrain/commit/b0c2a20e3be8aa161c17fea93ec06e95b2f0473c in debian 10?

**Comment by jorge-vitrubio** [comment]
I just did a fork from original.
Uploaded your functions and also added an installer sh for debian10 local. Please feel free to check jorge-vitrubio@96ef66a

I came up with this errors:

```bash
> mailtrain-client@2.0.0 css-minify /opt/mailtrain/client
> cleancss --level 1 --source-map --source-map-inline-sources --output dist/mailtrain.min.css dist/mailtrain.css

Hash: 68f928f33a645abad4e3
Version: webpack 4.41.5
Time: 992ms
Built at: 05/08/2021 1:14:24 AM
                        Asset      Size           Chunks             Chunk Names
             bootstrap.min.js  58.6 KiB                   [emitted]  
             ckeditor-root.js  7.62 KiB    ckeditor-root  [emitted]  ckeditor-root
           codeeditor-root.js  7.64 KiB  codeeditor-root  [emitted]  codeeditor-root
                coreui.min.js  31.1 KiB                   [emitted]  
             grapesjs-root.js  7.62 KiB    grapesjs-root  [emitted]  grapesjs-root
                jquery.min.js  86.1 KiB                   [emitted]  
              mosaico-root.js  7.61 KiB     mosaico-root  [emitted]  mosaico-root
                popper.min.js  20.8 KiB                   [emitted]  
                      root.js  7.37 KiB             root  [emitted]  root
   webfonts/fa-brands-400.eot   129 KiB                   [emitted]  
   webfonts/fa-brands-400.svg   692 KiB                   [emitted]  
   webfonts/fa-brands-400.ttf   129 KiB                   [emitted]  
  webfonts/fa-brands-400.woff    87 KiB                   [emitted]  
 webfonts/fa-brands-400.woff2  74.2 KiB                   [emitted]  
  webfonts/fa-regular-400.eot  33.6 KiB                   [emitted]  
  webfonts/fa-regular-400.svg   141 KiB                   [emitted]  
  webfonts/fa-regular-400.ttf  33.3 KiB                   [emitted]  
 webfonts/fa-regular-400.woff  16.4 KiB                   [emitted]  
webfonts/fa-regular-400.woff2  13.3 KiB                   [emitted]  
    webfonts/fa-solid-900.eot   190 KiB                   [emitted]  
    webfonts/fa-solid-900.svg   829 KiB                   [emitted]  
    webfonts/fa-solid-900.ttf   189 KiB                   [emitted]  
   webfonts/fa-solid-900.woff  96.7 KiB                   [emitted]  
  webfonts/fa-solid-900.woff2  74.3 KiB                   [emitted]  
Entrypoint root = root.js
Entrypoint mosaico-root = mosaico-root.js
Entrypoint ckeditor-root = ckeditor-root.js
Entrypoint grapesjs-root = grapesjs-root.js
Entrypoint codeeditor-root = codeeditor-root.js
[0] multi ./src/root.js 28 bytes {root} [built]
[1] multi ./src/lib/sandboxed-mosaico-root.js 28 bytes {mosaico-root} [built]
[2] multi ./src/lib/sandboxed-ckeditor-root.js 28 bytes {ckeditor-root} [built]
[3] multi ./src/lib/sandboxed-grapesjs-root.js 28 bytes {grapesjs-root} [built]
[4] multi ./src/lib/sandboxed-codeeditor-root.js 28 bytes {codeeditor-root} [built]
[./src/lib/sandboxed-ckeditor-root.js] 3.19 KiB {ckeditor-root} [built] [failed] [1 error]
[./src/lib/sandboxed-codeeditor-root.js] 3.19 KiB {codeeditor-root} [built] [failed] [1 error]
[./src/lib/sandboxed-grapesjs-root.js] 3.19 KiB {grapesjs-root} [built] [failed] [1 error]
[./src/lib/sandboxed-mosaico-root.js] 3.19 KiB {mosaico-root} [built] [failed] [1 error]
[./src/root.js] 3.19 KiB {root} [built] [failed] [1 error]

ERROR in ./src/root.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /opt/mailtrain/client/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at requireModule (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPreset (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
    at createDescriptor (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:58:104
    at cachedFunction (/opt/mailtrain/client/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/opt/mailtrain/client/node_modules/gensync/index.js:244:28)
    at sync (/opt/mailtrain/client/node_modules/gensync/index.js:84:14)
    at presets (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-chain.js:320:26)
 @ multi ./src/root.js root[0]

ERROR in ./src/lib/sandboxed-codeeditor-root.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /opt/mailtrain/client/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at requireModule (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPreset (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
    at createDescriptor (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:58:104
    at cachedFunction (/opt/mailtrain/client/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/opt/mailtrain/client/node_modules/gensync/index.js:244:28)
    at sync (/opt/mailtrain/client/node_modules/gensync/index.js:84:14)
    at presets (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-chain.js:320:26)
 @ multi ./src/lib/sandboxed-codeeditor-root.js codeeditor-root[0]

ERROR in ./src/lib/sandboxed-ckeditor-root.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /opt/mailtrain/client/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at requireModule (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPreset (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
    at createDescriptor (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:58:104
    at cachedFunction (/opt/mailtrain/client/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/opt/mailtrain/client/node_modules/gensync/index.js:244:28)
    at sync (/opt/mailtrain/client/node_modules/gensync/index.js:84:14)
    at presets (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-chain.js:320:26)
 @ multi ./src/lib/sandboxed-ckeditor-root.js ckeditor-root[0]

ERROR in ./src/lib/sandboxed-grapesjs-root.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /opt/mailtrain/client/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at requireModule (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPreset (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
    at createDescriptor (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:58:104
    at cachedFunction (/opt/mailtrain/client/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/opt/mailtrain/client/node_modules/gensync/index.js:244:28)
    at sync (/opt/mailtrain/client/node_modules/gensync/index.js:84:14)
    at presets (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-chain.js:320:26)
 @ multi ./src/lib/sandboxed-grapesjs-root.js grapesjs-root[0]

ERROR in ./src/lib/sandboxed-mosaico-root.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /opt/mailtrain/client/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/opt/mailtrain/client/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at requireModule (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPreset (/opt/mailtrain/client/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
    at createDescriptor (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at /opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:58:104
    at cachedFunction (/opt/mailtrain/client/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/opt/mailtrain/client/node_modules/gensync/index.js:244:28)
    at sync (/opt/mailtrain/client/node_modules/gensync/index.js:84:14)
    at presets (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
    at mergeChainOpts (/opt/mailtrain/client/node_modules/@babel/core/lib/config/config-chain.js:320:26)
 @ multi ./src/lib/sandboxed-mosaico-root.js mosaico-root[0]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mailtrain-client@2.0.0 js: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mailtrain-client@2.0.0 js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-07T23_14_24_869Z-debug.log
ERROR: "js" exited with 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mailtrain-client@2.0.0 build: `npm-run-all --parallel css js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mailtrain-client@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-07T23_14_24_976Z-debug.log
```

full log uploaded in commit jorge-vitrubio@c250d8e

**Comment by jorge-vitrubio** [comment]
Today I was checking this issue. Then I realized had nothing to do specifically with MailTrain but with Babel.

Might be related to: https://github.com/babel/babel/issues/11216

checked the `client/package.json` after upgrading min version from `^7.8.0` to `^7.8.4' errors disappear.
check commit jorge-vitrubio/mailtrain@4184c88

**Comment by joker-x** [comment]
I think you are right. Just updated npm packages in this commit: https://github.com/Mailtrain-org/mailtrain/pull/1065/commits/6373d7b5d09b4219ff29a2d182211caeb53855df (in the same pull request)

Can you check it?
