### ISSUE TITLE
Migration problem to upgrade Mailtrain v2 (2019) to v2 (2021-06-09)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [Mailtrain-org/mailtrain#1113]
Hi,
we tried to upgrade Mailtrain (from v2 working with docker image, installed in 2019) and we have an error on migration datatbase.

`ERR! Error: ER_NO_SUCH_TABLE: Table 'mailtrain.subscription__5' doesn't exist`

Do you have an idea of what is going on and what we can do to solved that ?

This is the log we have with the command `docker logs -f mailtrain_mailtrain_1`.

~~~
Info: Generating application/production.yaml
Info: LDAP not enabled
Info: CAS not enabled
Info: Generating server/production.yaml
Info: Waiting for MySQL Server
Info: Waiting for Redis Server
Info: Waiting for MongoDB Server
info sql Database check completed
migration file "20190722110000_hash_email.js" failed
migration failed with error: ALTER TABLE `subscription__5` MODIFY `hash_email` char(88) CHARACTER SET ascii - ER_NO_SUCH_TABLE: Table 'mailtrain.subscription__5' doesn't exist
ERR! Error: ER_NO_SUCH_TABLE: Table 'mailtrain.subscription__5' doesn't exist
ERR!     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
ERR!     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
ERR!     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
ERR!     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
ERR!     at Socket.emit (events.js:198:13)
ERR!     at addChunk (_stream_readable.js:288:12)
ERR!     at readableAddChunk (_stream_readable.js:269:11)
ERR!     at Socket.Readable.push (_stream_readable.js:224:10)
ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
ERR!     --------------------
ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
ERR!     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
ERR!     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
ERR!     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)
ERR!     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)
ERR!     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)
ERR!     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
ERR!     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
ERR!     at /app/server/node_modules/knex/lib/transaction.js:232:21
ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR!     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
ERR!     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
ERR!     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
ERR!     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR!     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
ERR!     at Runner.queryArray (/app/server/node_modules/knex/lib/runner.js:207:40)
ERR!  { Error: ER_NO_SUCH_TABLE: Table 'mailtrain.subscription__5' doesn't exist
ERR!     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
ERR!     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
ERR!     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
ERR!     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
ERR!     at Socket.emit (events.js:198:13)
ERR!     at addChunk (_stream_readable.js:288:12)
ERR!     at readableAddChunk (_stream_readable.js:269:11)
ERR!     at Socket.Readable.push (_stream_readable.js:224:10)
ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
ERR!     --------------------
ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
ERR!     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
ERR!     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
ERR!     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)
ERR!     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)
ERR!     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)
ERR!     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
ERR!     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
ERR!     at /app/server/node_modules/knex/lib/transaction.js:232:21
ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR!     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
ERR!     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
ERR!     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
ERR!     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR!     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
ERR!     at Runner.queryArray (/app/server/node_modules/knex/lib/runner.js:207:40)
ERR!   stack:
ERR!    'Error: ER_NO_SUCH_TABLE: Table \'mailtrain.subscription__5\' doesn\'t exist\n    at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)\n    at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)\n    at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)\n    at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n    --------------------\n    at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)\n    at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18\n    at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)\n    at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)\n    at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)\n    at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)\n    at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)\n    at /app/server/node_modules/knex/lib/transaction.js:232:21\n    at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)\n    at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)\n    at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)\n    at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)\n    at Runner.queryArray (/app/server/node_modules/knex/lib/runner.js:207:40)',
ERR!   code: 'ER_NO_SUCH_TABLE',
ERR!   errno: 1146,
ERR!   sqlMessage: 'Table \'mailtrain.subscription__5\' doesn\'t exist',
ERR!   sqlState: '42S02',
ERR!   index: 0,
ERR!   sql:
ERR!    'ALTER TABLE `subscription__5` MODIFY `hash_email` char(88) CHARACTER SET ascii' }
~~~

**Comment by PhilippeAccorsi** [comment]
in the database, I just have this list of subscription tables
~~~
| subscription__1                |
| subscription__10               |
| subscription__13               |
| subscription__16               |
| subscription__19               |
| subscription__21               |
| subscription__28               |
| subscription__3                |
| subscription__4|
~~~

**Comment by PhilippeAccorsi** [comment]
I can't restart directly with the old docker images because I have the error 
~~~
ERR! Error: The migration directory is corrupt, the following files are missing: 20190615000000_generalization_of_queued_and_file_locking.js, 20190616000000_drop_subject_in_send_configurations.js, 20190629000000_add_start_at_to_campaigns.js, 20190629170000_generalization_of_queued.js, 20190630210000_tag_language.js, 20190705220000_test_messages.js
~~~

What I need to do ? 
- erase database and restore dump ?
- erase some files ?

**Comment by PhilippeAccorsi** [comment]
I have tried to :
1 - delete bdd
2 - restore dump
3 - start with old docker images

But 2 informations:
- mailtrain reply but I just seen blanck page (mailtrain try to find file on localhost and not use the url of serveur. We use a proxy in front of docker (and not change docker-compose configuration).
- in mailtrain log I can see this:
~~~
info Using local auth 
info sql Database check completed
info Executor Executor process started.
info ZoneMTA Starting built-in Zone MTA process
info ZoneMTA ZoneMTA process started
info Express WWW server [trusted] listening on port 3000
info Express WWW server [sandbox] listening on port 3003
info Express WWW server [public] listening on port 3004
info Importer Importer process started
info Feed Feedcheck process started
info Senders Worker process 1 started
info Senders Worker process 2 started
info Senders Worker process 4 started
info Senders Worker process 0 started
info Senders Worker process 3 started
info Senders Master sender process started
info Triggers Starting trigger check service
info GDPR Starting GDPR cleanup service
info ReportProcessor Trying to start worker because runningWorkersCount=0 maxWorkersCount=1
info ReportProcessor No more reports to start a worker for
info Service All services started
ERR! GDPR Error: ER_NO_SUCH_TABLE: Table 'mailtrain.subscription__5' doesn't exist
ERR! GDPR     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
ERR! GDPR     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
ERR! GDPR     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
ERR! GDPR     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
ERR! GDPR     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
ERR! GDPR     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
ERR! GDPR     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
ERR! GDPR     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
ERR! GDPR     at Socket.emit (events.js:182:13)
ERR! GDPR     at Socket.EventEmitter.emit (domain.js:441:20)
ERR! GDPR     at addChunk (_stream_readable.js:283:12)
ERR! GDPR     at readableAddChunk (_stream_readable.js:264:11)
ERR! GDPR     at Socket.Readable.push (_stream_readable.js:219:10)
ERR! GDPR     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
ERR! GDPR     --------------------
ERR! GDPR     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
ERR! GDPR     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
ERR! GDPR     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
ERR! GDPR     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:313:9)
ERR! GDPR     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:483:18)
ERR! GDPR     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:79:10)
ERR! GDPR     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
ERR! GDPR     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
ERR! GDPR     at /app/server/node_modules/knex/lib/transaction.js:232:21
ERR! GDPR     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR! GDPR     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
ERR! GDPR     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
ERR! GDPR     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
ERR! GDPR     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR! GDPR     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
ERR! GDPR     at /app/server/node_modules/knex/lib/runner.js:47:21
ERR! GDPR     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR! GDPR     at /app/server/node_modules/bluebird/js/release/using.js:185:26
ERR! GDPR     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR! GDPR     at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:512:31)
ERR! GDPR     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:569:18)
ERR! GDPR     at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:614:10)
ERR! GDPR  { Error: ER_NO_SUCH_TABLE: Table 'mailtrain.subscription__5' doesn't exist
ERR! GDPR     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
ERR! GDPR     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
ERR! GDPR     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
ERR! GDPR     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
ERR! GDPR     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
ERR! GDPR     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
ERR! GDPR     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
ERR! GDPR     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
ERR! GDPR     at Socket.emit (events.js:182:13)
ERR! GDPR     at Socket.EventEmitter.emit (domain.js:441:20)
ERR! GDPR     at addChunk (_stream_readable.js:283:12)
ERR! GDPR     at readableAddChunk (_stream_readable.js:264:11)
ERR! GDPR     at Socket.Readable.push (_stream_readable.js:219:10)
ERR! GDPR     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
ERR! GDPR     --------------------
ERR! GDPR     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
ERR! GDPR     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
ERR! GDPR     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
ERR! GDPR     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:313:9)
ERR! GDPR     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:483:18)
ERR! GDPR     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:79:10)
ERR! GDPR     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
ERR! GDPR     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
ERR! GDPR     at /app/server/node_modules/knex/lib/transaction.js:232:21
ERR! GDPR     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR! GDPR     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
ERR! GDPR     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
ERR! GDPR     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
ERR! GDPR     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR! GDPR     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
ERR! GDPR     at /app/server/node_modules/knex/lib/runner.js:47:21
ERR! GDPR     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR! GDPR     at /app/server/node_modules/bluebird/js/release/using.js:185:26
ERR! GDPR     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
ERR! GDPR     at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:512:31)
ERR! GDPR     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:569:18)
ERR! GDPR     at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:614:10)
ERR! GDPR   stack:
ERR! GDPR    'Error: ER_NO_SUCH_TABLE: Table \'mailtrain.subscription__5\' doesn\'t exist\n    at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)\n    at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)\n    at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)\n    at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n    --------------------\n    at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)\n    at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18\n    at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:313:9)\n    at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:483:18)\n    at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:79:10)\n    at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)\n    at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)\n    at /app/server/node_modules/knex/lib/transaction.js:232:21\n    at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)\n    at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)\n    at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)\n    at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)\n    at /app/server/node_modules/knex/lib/runner.js:47:21\n    at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at /app/server/node_modules/bluebird/js/release/using.js:185:26\n    at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:614:10)',
ERR! GDPR   code: 'ER_NO_SUCH_TABLE',
ERR! GDPR   errno: 1146,
ERR! GDPR   sqlMessage: 'Table \'mailtrain.subscription__5\' doesn\'t exist',
ERR! GDPR   sqlState: '42S02',
ERR! GDPR   index: 0,
ERR! GDPR   sql:
ERR! GDPR    'delete from `subscription__5` where `status` in (2, 4) and `unsubscribed` <= \'2021-06-01 15:04:10.333\'' }
~~~

This is still not exist in my database, I not really understund why mailtrain try to access on that `subscription__5`.

**Comment by PhilippeAccorsi** [comment]
So for the error of blank page is because on old v2 docker instllation we need to start with this kind of command:

~~~
MAILTRAIN_SETTINGS="--trustedUrlBase https://mailtrain.domain.fr --sandboxUrlBase https://sboxmailtrain.domain.fr --publicUrlBase https://lists.domain.fr --withProxy" docker-compose up -d
~~~

I seen that now the readm.md inform how add value with environement variable directly on docker-compose.yml.

So for me the problem to migrate is:
- what i need to do to repair the missing `subscription__x` table (cf my list of table https://github.com/Mailtrain-org/mailtrain/issues/1113#issuecomment-872316231 )

**Comment by PhilippeAccorsi** [comment]
The docker image I used on production actually is on commit `https://github.com/Mailtrain-org/mailtrain/commit/75138f9728e1709e9331e6decfe980979de0ecc3`.

I have checked and on this installation I have also some error visible about `subscription__x` table.

- What kind of procedure can I use to clean and migrate installation ? 
- Is it possible to dump all data (dump of mysql its ok but I dont know if I need to dump mongo and redis) and restore on new installation ?

**Comment by PhilippeAccorsi** [comment]
🆙 

- Do you have an idea about the problem ?
- Do you a procedure to migrate instance ?

**Comment by bures** [comment]
Hard to say. What surprises me is that the subscription_5 table is completely missing in your DB before migration (at least this is what I gathered from your report). It might be that your DB has been corrupt even before the migration. Could you send me the list of all tables you have in your DB (before migration) and the content of the `lists` table. I'll check it. You can send it to me directly if you don't want to share it here in public.

**Comment by PhilippeAccorsi** [comment]
Sorry I was on holiday :)

this is the list of tables visible in MariaDB
|Tables_in_mailtrain|
|--|
| subscription__1                |
| subscription__10               |
| subscription__13               |
| subscription__16               |
| subscription__19               |
| subscription__21               |
| subscription__28               |
| subscription__3                |
| subscription__4                |

And `select * from lists;` (I have changed the name visible in "name" "description" and email and url)

| id | cid | default_form | name | description | subscribers | created | public_subscribe | unsubscription_mode | listunsubscribe_disabled | namespace | contact_email | homepage | to_name | send_configuration |
|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|
|  1 | rmF_Yr7Af |NULL | perso1| perso1|14 | 2019-07-22 09:43:09 |1 |0 |0 |1 ||| [MERGE_FIRST_NAME] [MERGE_LAST_NAME]|2|
|  3 | -860UN_C5 |NULL | perso2| perso2|8 | 2019-07-22 09:44:13 |1 |0 |0 |1 ||| [MERGE_FIRST_NAME] [MERGE_LAST_NAME]|2|
|  4 | gKAoTram1 |NULL | perso3| perso3|134 | 2019-07-22 09:44:45 |1 |1 |0 |1 ||| [MERGE_FIRST_NAME] [MERGE_LAST_NAME]|2|
|  5 | HYde5s_FR |NULL | Tests - Suppression impossible ||0 | 2019-07-23 07:03:52 |1 |0 |0 |1 ||| [MERGE_FIRST_NAME] [MERGE_LAST_NAME]|2|
| 10 | NMWVuvKP6 |2 | perso4| perso4|169 | 2019-10-16 13:23:48 |1 |1 |0 |1 | xxx@xxx.fr | https://xxx.fr| [MERGE_NAME]|2|
| 13 | tjkJdHbrc |NULL | perso5| perso5|54 | 2019-11-08 14:59:21 |1 |0 |0 |1 ||| [MERGE_FIRST_NAME] [MERGE_LAST_NAME]|2|
| 16 | 1--NsZocP |2 | perso6| perso6 |0 | 2020-01-14 13:11:41 |0 |1 |0 |1 | xxx@xxx.fr | https://xxx.fr | [MERGE_NAME]|2|
| 19 | aVmcyg-ji |4 | perso7| perso7|5 | 2020-01-30 13:22:12 |1 |1 |0 |1 | xxx@xxx.fr || [MERGE_NAME]|2|
| 21 | DyP-I3MLv |5 | perso8| perso8|13 | 2020-03-13 16:44:38 |1 |0 |0 |1 ||| [MERGE_FIRST_NAME] [MERGE_LAST_NAME]|1|
| 28 | JVm_jVzWQ |NULL | damien - a supprimer| A supprimer|1 | 2021-05-20 10:23:57 |1 |0 |0 |1 ||| [MERGE_FIRST_NAME] [MERGE_LAST_NAME]|2|

**Comment by PhilippeAccorsi** [comment]
@bures When I seen this, I think something is broken about `subscription__5` and maybe it is the reason why I can't delete list with `id = 5`. But do you think it is possible to just delete list with id 5 directly in the database or more table can have some information about this list ?

**Comment by bures** [comment]
Unless you created any segements, triggers, fields for the list, it should be enough to just delete the row in `lists` table. If you created any custom fields, delete also the related rows in that table.

**Comment by PhilippeAccorsi** [comment]
Ok. I try this tomorrow and I come back here to give result.
Thanks

**Comment by PhilippeAccorsi** [comment]
Hi,

I have clean my database with this commands lines:
~~~
begin;
select * from custom_fields where list = 5;
delete from custom_fields where list = 5;
delete from lists where id = 5;
select * from lists;
commit;
~~~

The migration is completed correctly. Mailtrain is now working good \o/
Thanks for your help.

**Comment by bures** [comment]
Perfect. Thanks. I guess we can close this issue now. if any problem resurfaces, please feel feel to reopen it.
