### ISSUE TITLE
migration file "20170506102634_v1_to_v2.js" failed

### ISSUE THREAD

**Issue by thomas-pike** [Mailtrain-org/mailtrain#1128]
Upgrading from mailtrain v1 to v2, failed (after several hours migrating data) on migration file `20170506102634_v1_to_v2.js` with the following error:

```
migration failed with error: insert into `campaign_lists` (`campaign`, `list`, `segment`) values (14, 2, 18) - ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`mailtrain`.`campaign_lists`, CONSTRAINT `campaign_lists_segment_foreign` FOREIGN KEY (`segment`) REFERENCES `segments` (`id`))
ERR! Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`mailtrain`.`campaign_lists`, CONSTRAINT `campaign_lists_segment_foreign` FOREIGN KEY (`segment`) REFERENCES `segments` (`id`))
```

There was indeed no record in the segments table with an id of 18.

Repeat attempts of the migration then fail with:

```migration file "20170506102634_v1_to_v2.js" failed
migration failed with error: Cannot read property 'value' of undefined
ERR! TypeError: Cannot read property 'value' of undefined
ERR!     at migrateBase (/opt/mailtrain/server/setup/knex/migrations/20170506102634_v1_to_v2.js:84:65)
ERR!     at async /opt/mailtrain/server/setup/knex/migrations/20170506102634_v1_to_v2.js:1280:5
ERR!  TypeError: Cannot read property 'value' of undefined
ERR!     at migrateBase (/opt/mailtrain/server/setup/knex/migrations/20170506102634_v1_to_v2.js:84:65)
ERR!     at async /opt/mailtrain/server/setup/knex/migrations/20170506102634_v1_to_v2.js:1280:5```

**Comment by thomas-pike** [comment]
Full stacktrace of the error:
```
Aug 07 11:41:02 mailtrain.viv.dc01 node[28709]: info sql Database check completed
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: migration file "20170506102634_v1_to_v2.js" failed
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: migration failed with error: insert into `campaign_lists` (`campaign`, `list`, `segment`) values (14, 2, 18) - ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`mailtrain`.`campaign_lists`, CONSTRAINT `campaign_lists_segment_foreign` FOREIGN KEY (`segment`) REFERENCES `segments` (`id`))
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR! Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`mailtrain`.`campaign_lists`, CONSTRAINT `campaign_lists_segment_foreign` FOREIGN KEY (`segment`) REFERENCES `segments` (`id`))
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Query.Sequence._packetToError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Query.ErrorPacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Protocol._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Parser._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Parser.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Protocol.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:91:28)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.emit (events.js:400:28)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.emit (domain.js:470:12)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at addChunk (internal/streams/readable.js:290:12)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at readableAddChunk (internal/streams/readable.js:265:9)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.Readable.push (internal/streams/readable.js:204:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     --------------------
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Protocol._enqueue (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Connection.query (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:201:25)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._execute (/opt/mailtrain/server/node_modules/bluebird/js/release/debuggability.js:384:9)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._resolveFromExecutor (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:518:18)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at new Promise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:103:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Client_MySQL._query (/opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Client_MySQL.query (/opt/mailtrain/server/node_modules/knex/lib/client.js:192:17)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/transaction.js:232:21
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Function.Promise.attempt.Promise.try (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:39:29)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Client_MySQL.trxClient.query (/opt/mailtrain/server/node_modules/knex/lib/transaction.js:229:33)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Runner.<anonymous> (/opt/mailtrain/server/node_modules/knex/lib/runner.js:138:36)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Runner.tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Runner.query (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:15:34)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/runner.js:47:21
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at /opt/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._settlePromiseFromHandler (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:547:31)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._settlePromise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:604:18)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._settlePromise0 (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!  Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`mailtrain`.`campaign_lists`, CONSTRAINT `campaign_lists_segment_foreign` FOREIGN KEY (`segment`) REFERENCES `segments` (`id`))
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Query.Sequence._packetToError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Query.ErrorPacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Protocol._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Parser._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Parser.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Protocol.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:91:28)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.emit (events.js:400:28)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.emit (domain.js:470:12)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at addChunk (internal/streams/readable.js:290:12)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at readableAddChunk (internal/streams/readable.js:265:9)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Socket.Readable.push (internal/streams/readable.js:204:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     --------------------
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Protocol._enqueue (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Connection.query (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:201:25)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._execute (/opt/mailtrain/server/node_modules/bluebird/js/release/debuggability.js:384:9)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._resolveFromExecutor (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:518:18)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at new Promise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:103:10)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Client_MySQL._query (/opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Client_MySQL.query (/opt/mailtrain/server/node_modules/knex/lib/client.js:192:17)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/transaction.js:232:21
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Function.Promise.attempt.Promise.try (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:39:29)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Client_MySQL.trxClient.query (/opt/mailtrain/server/node_modules/knex/lib/transaction.js:229:33)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Runner.<anonymous> (/opt/mailtrain/server/node_modules/knex/lib/runner.js:138:36)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Runner.tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Runner.query (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:15:34)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/runner.js:47:21
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at /opt/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._settlePromiseFromHandler (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:547:31)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._settlePromise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:604:18)
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!     at Promise._settlePromise0 (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10) {
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!   code: 'ER_NO_REFERENCED_ROW_2',
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!   errno: 1452,
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!   sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`mailtrain`.`campaign_lists`, CONSTRAINT `campaign_lists_segment_foreign` FOREIGN KEY (`segment`) REFERENCES `segments` (`id`))',
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!   sqlState: '23000',
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!   index: 0,
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR!   sql: 'insert into `campaign_lists` (`campaign`, `list`, `segment`) values (14, 2, 18)'
Aug 07 19:33:50 mailtrain.viv.dc01 node[28709]: ERR! }
```

**Comment by bures** [comment]
Could it be that your db in V1 is already inconsistent? If it is so, I'd suggest to delete or create entries to make it consistent. The missing segment is suspicious

**Comment by thomas-pike** [comment]
It's certainly possible. Where in the original schema could the source of such an inconsistency be? I see the `segments` table existed in v1, but the `campaign_lists` table did not. Which v1 table was being migrated from?

**Comment by bures** [comment]
`campaign_lists` is a new table. In v1, the campaign was associated only with one pair <list,segment>. In v2, you can deliver to multiple <list, segment>. Thus campaign's columns `list` and `segment` are now in the separate `campaign_lists` table. It seems that you have a campaign that references a segment that does not exist any more. The easiest solution is to set the column `segment` in that campaign to NULL. Then re-try the migration.

**Comment by forgeOneHQ** [comment]
@thomas-pike if you still struggle you are welcome to open a new issue. Please also give us all infos like OS (Docker or directly deployment), db versions you use, logfiles and config files.
