### ISSUE TITLE
20200824160149_convert_to_utf8mb4.js causes error

### ISSUE THREAD

**Issue by dmastrorillo** [Mailtrain-org/mailtrain#1141]
# Setup

I am using an ec2 instance connected to an RDS running mySql. Mailtrain is running inside of docker with nginx acting as a reverse proxy.

## How I installed mailtrain

I created the docker-compose.yml and the .env file and ran `docker-compose up -d`

## versions

- Docker version 20.10.8, build 3967b7d
- docker-compose version 1.29.2, build 5becea4c
- mailtrain version mailtrain/mailtrain:latest
- mySQL version 8.0.23

## .env file

- WWW_PROXY=true
- MYSQL_USER=[redacted]
- MYSQL_PASSWORD=[redacted]
- MYSQL_HOST=[redacted]
- WITH_REDIS=false
- WITH_ZONE_MTA=false

## docker-compose.yml

```yml
version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin:${PHP_VERSION}
    restart: always
    ports:
      - 8080:80
    environment:
            - PMA_ABSOLUTE_URI
            - PMA_HOST
  mailtrain:
    image: mailtrain/mailtrain:latest
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files
    environment:
    - WWW_PROXY
    - MYSQL_USER
    - MYSQL_PASSWORD
    - MYSQL_HOST
    - MAILTRAIN_VERSION
    - WITH_REDIS
    - WITH_ZONE_MTA


volumes:
  mailtrain-files:
```

## error

```log
mailtrain_1   | Info: Generating application/production.yaml
mailtrain_1   | Info: LDAP not enabled
mailtrain_1   | Info: CAS not enabled
mailtrain_1   | Info: Generating server/production.yaml
mailtrain_1   | Info: Waiting for MySQL Server
mailtrain_1   | info sql SQL not set up, initializing
mailtrain_1   | info sql Loading tables from mailtrain.sql
mailtrain_1   | info sql Database check completed
mailtrain_1   | migration file "20200824160149_convert_to_utf8mb4.js" failed
mailtrain_1   | migration failed with error: ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci; - ER_NO_SUCH_TABLE: Table 'mailtrain.undefined' doesn't exist
mailtrain_1   | ERR! Error: ER_NO_SUCH_TABLE: Table 'mailtrain.undefined' doesn't exist
mailtrain_1   | ERR!     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
mailtrain_1   | ERR!     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
mailtrain_1   | ERR!     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
mailtrain_1   | ERR!     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
mailtrain_1   | ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
mailtrain_1   | ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
mailtrain_1   | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
mailtrain_1   | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
mailtrain_1   | ERR!     at Socket.emit (events.js:198:13)
mailtrain_1   | ERR!     at addChunk (_stream_readable.js:288:12)
mailtrain_1   | ERR!     at readableAddChunk (_stream_readable.js:269:11)
mailtrain_1   | ERR!     at Socket.Readable.push (_stream_readable.js:224:10)
mailtrain_1   | ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
mailtrain_1   | ERR!     --------------------
mailtrain_1   | ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mailtrain_1   | ERR!     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
mailtrain_1   | ERR!     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
mailtrain_1   | ERR!     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)
mailtrain_1   | ERR!     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)
mailtrain_1   | ERR!     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)
mailtrain_1   | ERR!     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
mailtrain_1   | ERR!     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
mailtrain_1   | ERR!     at /app/server/node_modules/knex/lib/transaction.js:232:21
mailtrain_1   | ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1   | ERR!     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
mailtrain_1   | ERR!     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
mailtrain_1   | ERR!     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
mailtrain_1   | ERR!     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1   | ERR!     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
mailtrain_1   | ERR!     at /app/server/node_modules/knex/lib/runner.js:47:21
mailtrain_1   | ERR!  { Error: ER_NO_SUCH_TABLE: Table 'mailtrain.undefined' doesn't exist
mailtrain_1   | ERR!     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
mailtrain_1   | ERR!     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
mailtrain_1   | ERR!     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
mailtrain_1   | ERR!     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
mailtrain_1   | ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
mailtrain_1   | ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
mailtrain_1   | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
mailtrain_1   | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
mailtrain_1   | ERR!     at Socket.emit (events.js:198:13)
mailtrain_1   | ERR!     at addChunk (_stream_readable.js:288:12)
mailtrain_1   | ERR!     at readableAddChunk (_stream_readable.js:269:11)
mailtrain_1   | ERR!     at Socket.Readable.push (_stream_readable.js:224:10)
mailtrain_1   | ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
mailtrain_1   | ERR!     --------------------
mailtrain_1   | ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mailtrain_1   | ERR!     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
mailtrain_1   | ERR!     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
mailtrain_1   | ERR!     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)
mailtrain_1   | ERR!     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)
mailtrain_1   | ERR!     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)
mailtrain_1   | ERR!     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
mailtrain_1   | ERR!     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
mailtrain_1   | ERR!     at /app/server/node_modules/knex/lib/transaction.js:232:21
mailtrain_1   | ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1   | ERR!     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
mailtrain_1   | ERR!     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
mailtrain_1   | ERR!     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
mailtrain_1   | ERR!     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1   | ERR!     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
mailtrain_1   | ERR!     at /app/server/node_modules/knex/lib/runner.js:47:21
mailtrain_1   | ERR!   stack:
mailtrain_1   | ERR!    'Error: ER_NO_SUCH_TABLE: Table \'mailtrain.undefined\' doesn\'t exist\n    at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)\n    at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)\n    at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)\n    at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n    --------------------\n    at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)\n    at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18\n    at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)\n    at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)\n    at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)\n    at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)\n    at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)\n    at /app/server/node_modules/knex/lib/transaction.js:232:21\n    at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)\n    at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)\n    at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)\n    at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)\n    at /app/server/node_modules/knex/lib/runner.js:47:21',
mailtrain_1   | ERR!   code: 'ER_NO_SUCH_TABLE',
mailtrain_1   | ERR!   errno: 1146,
mailtrain_1   | ERR!   sqlMessage: 'Table \'mailtrain.undefined\' doesn\'t exist',
mailtrain_1   | ERR!   sqlState: '42S02',
mailtrain_1   | ERR!   index: 0,
mailtrain_1   | ERR!   sql:
mailtrain_1   | ERR!    'ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE undefined CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;' }
stack_mailtrain_1 exited with code 1

```
## Possible issue

**mailtrain/server/setup/knex/migrations/20200824160149_convert_to_utf8mb4.js**

```js
exports.up = function(knex, Promise) {
  return knex.raw('SELECT table_name FROM information_schema.tables WHERE table_schema = ?', [knex.client.database()])
    .then(function(tablas) {
       let sql="";
       tablas=tablas[0];
       for(let i=0; i<tablas.length; i++) {
	 sql+="ALTER TABLE "+tablas[i].table_name+" CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;";
       }
       //console.log(sql);
       return knex.raw(sql);
    });
};
```

`tablas[i].table_name` seems to always return undefined although the tables are created and exist in the db.

**Comment by joker-x** [comment]
@danyy1996 Can you try overwritten the migration file with this code:
```
exports.up = function(knex, Promise) {
  return knex.raw('SELECT table_name FROM information_schema.tables WHERE table_schema = ?', [knex.client.database()])
    .then(function(tablas) {
       let sql="";
       tablas=tablas[0];
       for(let i=0; i<tablas.length; i++) {
         let tablename=tablas[i].table_name;
	 if (tablename) sql+="ALTER TABLE "+tablename+" CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;";
       }
       //console.log(sql);
       return knex.raw(sql);
    });
};
```

**Comment by bures** [comment]
@joker-x Any idea why the table name would not be defined? It seems strange to me.

**Comment by joker-x** [comment]
Maybe the sentence 'SELECT table_name FROM information_schema.tables WHERE table_schema = ?' not working exactly in MySQL 8 and in MariaDB 10?

**Comment by bures** [comment]
Could be.

**Comment by jfqd** [comment]
The following fixed it for me with percona mysql 8:

```
sed -i \
    -e "s|].table_name|].TABLE_NAME|" \
    server/setup/knex/migrations/20200824160149_convert_to_utf8mb4.js
```

**Comment by terion-name** [comment]
> The following fixed it for me with percona mysql 8:
> 
> ```
> sed -i \
>     -e "s|].table_name|].TABLE_NAME|" \
>     server/setup/knex/migrations/20200824160149_convert_to_utf8mb4.js
> ```

kinda should be added to production? @joker-x ?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
