### ISSUE TITLE
Mailtrain v2 - Update of server and client produce issue on zone-mta

### ISSUE THREAD

**Issue by forgeOneHQ** [Mailtrain-org/mailtrain#1142]
I tried to update the mailtrain server and client and after all is running fine again, the mailing is not working anymore. Zone-MTA was not updated before, same issue after the updated, so I expect an issue  in between.

```
Aug 29 19:25:56 news01.example.com node[343885]: info HTTP PUT /rest/restricted-access-token 200 14.797 ms - -
Aug 29 19:25:57 news01.example.com node[346527]: undefined:1
Aug 29 19:25:57 news01.example.com node[346527]: =?UTF-8?Q?=7B=22domainName=22=3A=22example?= =?UTF-8?Q?=2Eat=22=2C=22keySelector=22=3A=222019>
Aug 29 19:25:57 news01.example.com node[346527]: SyntaxError: Unexpected token = in JSON at position 0
Aug 29 19:25:57 news01.example.com node[346527]:     at JSON.parse (<anonymous>)
Aug 29 19:25:57 news01.example.com node[346527]:     at Object.app.addHook [as action] (/opt/mailtrain/zone-mta/plugins/mailtrain-receiver.js:19:34)
Aug 29 19:25:57 news01.example.com node[346527]:     at Immediate.checkNext (/opt/mailtrain/zone-mta/node_modules/zone-mta/lib/plugin-handler.js:427:2>
Aug 29 19:25:57 news01.example.com node[346527]:     at runCallback (timers.js:705:18)
Aug 29 19:25:57 news01.example.com node[346527]:     at tryOnImmediate (timers.js:676:5)
Aug 29 19:25:57 news01.example.com node[346527]:     at processImmediate (timers.js:658:5)
Aug 29 19:25:57 news01.example.com node[343909]: ERR! SMTP/feeder/346527 Reciver process 9a4d24ffefb35f696515 for feeder exited with 1
Aug 29 19:25:57 news01.example.com node[344005]: ERR! Senders Sending message to 13:122 failed with error: write EPIPE. Dropping the message.
Aug 29 19:26:26 news01.example.com node[343885]: info HTTP PUT /rest/restricted-access-token 200 11.134 ms - -
Aug 29 19:26:34 news01.example.com node[346622]: undefined:1
Aug 29 19:26:34 news01.example.com node[346622]: =?UTF-8?Q?=7B=22domainName=22=3A=22example?= =?UTF-8?Q?=2Eat=22=2C=22keySelector=22=3A=222019>
Aug 29 19:26:34 news01.example.com node[346622]: SyntaxError: Unexpected token = in JSON at position 0
Aug 29 19:26:34 news01.example.com node[346622]:     at JSON.parse (<anonymous>)
Aug 29 19:26:34 news01.example.com node[346622]:     at Object.app.addHook [as action] (/opt/mailtrain/zone-mta/plugins/mailtrain-receiver.js:19:34)
Aug 29 19:26:34 news01.example.com node[346622]:     at Immediate.checkNext (/opt/mailtrain/zone-mta/node_modules/zone-mta/lib/plugin-handler.js:427:2>
Aug 29 19:26:34 news01.example.com node[346622]:     at runCallback (timers.js:705:18)
Aug 29 19:26:34 news01.example.com node[346622]:     at tryOnImmediate (timers.js:676:5)
Aug 29 19:26:34 news01.example.com node[346622]:     at processImmediate (timers.js:658:5)
Aug 29 19:26:34 news01.example.com node[343909]: ERR! SMTP/feeder/346622 Reciver process 92f9fdebad91139a877e for feeder exited with 1
Aug 29 19:26:34 news01.example.com node[344020]: ERR! Senders Sending message to 13:122 failed with error: read ECONNRESET. Dropping the message.
```

**Comment by bures** [comment]
Please, make repo or PR that has this issue, so that I can pull it. I'll then take a look at it.

**Comment by forgeOneHQ** [comment]
After investigating I still see no issue now. The issue comes itself from a special configuration for Sending on the webinterface.

I am investigating closer since the isse already happened earlier.

**Comment by forgeOneHQ** [comment]
Closing, I will try to debug it closer if it happens again.
