### ISSUE TITLE
Migrating from v1 to v2 with docker compose

### ISSUE THREAD

**Issue by Moritz-Schmidt** [Mailtrain-org/mailtrain#1145]
hey!

im trying to migrate from v1 to v2 in Docker (with docker compose)
I did what @bures said over here: https://github.com/Mailtrain-org/mailtrain/issues/1144#issuecomment-910062849
I got the following Error:

```
mailtrain_1  | info sql Database check completed
mailtrain_1  | migration file "20170506102634_v1_to_v2.js" failed
mailtrain_1  | migration failed with error: select `id`, `filename`, `originalname` from `files_campaign_attachment` where `entity` = 6 and `delete_pending` = false - ER_BAD_FIELD_ERROR: Unknown column 'delete_pending' in 'where clause'
mailtrain_1  | ERR! Error: ER_BAD_FIELD_ERROR: Unknown column 'delete_pending' in 'where clause'
mailtrain_1  | ERR!     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
mailtrain_1  | ERR!     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
mailtrain_1  | ERR!     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
mailtrain_1  | ERR!     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
mailtrain_1  | ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
mailtrain_1  | ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
mailtrain_1  | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
mailtrain_1  | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
mailtrain_1  | ERR!     at Socket.emit (events.js:198:13)
mailtrain_1  | ERR!     at addChunk (_stream_readable.js:288:12)
mailtrain_1  | ERR!     at readableAddChunk (_stream_readable.js:269:11)
mailtrain_1  | ERR!     at Socket.Readable.push (_stream_readable.js:224:10)
mailtrain_1  | ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
mailtrain_1  | ERR!     --------------------
mailtrain_1  | ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mailtrain_1  | ERR!     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
mailtrain_1  | ERR!     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
mailtrain_1  | ERR!     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)
mailtrain_1  | ERR!     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)
mailtrain_1  | ERR!     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)
mailtrain_1  | ERR!     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
mailtrain_1  | ERR!     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
mailtrain_1  | ERR!     at /app/server/node_modules/knex/lib/transaction.js:232:21
mailtrain_1  | ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
mailtrain_1  | ERR!     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
mailtrain_1  | ERR!     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
mailtrain_1  | ERR!     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
mailtrain_1  | ERR!     at /app/server/node_modules/knex/lib/runner.js:47:21
mailtrain_1  | ERR!  { Error: ER_BAD_FIELD_ERROR: Unknown column 'delete_pending' in 'where clause'
mailtrain_1  | ERR!     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
mailtrain_1  | ERR!     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
mailtrain_1  | ERR!     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
mailtrain_1  | ERR!     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
mailtrain_1  | ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
mailtrain_1  | ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
mailtrain_1  | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
mailtrain_1  | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
mailtrain_1  | ERR!     at Socket.emit (events.js:198:13)
mailtrain_1  | ERR!     at addChunk (_stream_readable.js:288:12)
mailtrain_1  | ERR!     at readableAddChunk (_stream_readable.js:269:11)
mailtrain_1  | ERR!     at Socket.Readable.push (_stream_readable.js:224:10)
mailtrain_1  | ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
mailtrain_1  | ERR!     --------------------
mailtrain_1  | ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mailtrain_1  | ERR!     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
mailtrain_1  | ERR!     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
mailtrain_1  | ERR!     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)
mailtrain_1  | ERR!     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)
mailtrain_1  | ERR!     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)
mailtrain_1  | ERR!     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
mailtrain_1  | ERR!     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
mailtrain_1  | ERR!     at /app/server/node_modules/knex/lib/transaction.js:232:21
mailtrain_1  | ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
mailtrain_1  | ERR!     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
mailtrain_1  | ERR!     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
mailtrain_1  | ERR!     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
mailtrain_1  | ERR!     at /app/server/node_modules/knex/lib/runner.js:47:21
mailtrain_1  | ERR!   stack:
mailtrain_1  | ERR!    'Error: ER_BAD_FIELD_ERROR: Unknown column \'delete_pending\' in \'where clause\'\n    at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)\n    at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)\n    at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)\n    at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n    --------------------\n    at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)\n    at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18\n    at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)\n    at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)\n    at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)\n    at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)\n    at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)\n    at /app/server/node_modules/knex/lib/transaction.js:232:21\n    at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)\n    at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)\n    at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)\n    at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)\n    at /app/server/node_modules/knex/lib/runner.js:47:21',
mailtrain_1  | ERR!   code: 'ER_BAD_FIELD_ERROR',
mailtrain_1  | ERR!   errno: 1054,
mailtrain_1  | ERR!   sqlMessage: 'Unknown column \'delete_pending\' in \'where clause\'',
mailtrain_1  | ERR!   sqlState: '42S22',
mailtrain_1  | ERR!   index: 0,
mailtrain_1  | ERR!   sql:
mailtrain_1  | ERR!    'select `id`, `filename`, `originalname` from `files_campaign_attachment` where `entity` = 6 and `delete_pending` = false' }
```

the old version (v1) is 1.24.0
any help?
thanks!

**Comment by bures** [comment]
Indeed. It seems that we have not correctly covered the case when you migrate a campaign that has attachments.

I can take a look at it and fix it, but it has low priority for me as my systems don't need the v1->v2 migration. If anyone wanted to speed this up, it would help me if you could provide some minimal version of v1 database with campaign that has an attachment (and thus fails the migration).

**Comment by Moritz-Schmidt** [comment]
I don't necessarily need to migrate the campaigns with an attachment, do you know any fix to just solve this problem without migrating the attachments?

**Comment by bures** [comment]
If those are just a few campaigns, delete the attachments through the UI.

**Comment by bures** [comment]
In v1 I mean. If there are more of them, you may delete them directly in the db using SQL.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
