### ISSUE TITLE
Mailtrain not working after fresh install on Ubuntu 18.04

### ISSUE THREAD

**Issue by RomainFallet** [Mailtrain-org/mailtrain#1165]
Hardware :
2vCPU
4 GO RAM

Distribution:
Ubuntu 18.04 (fresh install)

I ran the install script from the README with public URLs, everything goes fine, TLS certificates are generated, the install script says "success". But the login URL says:

```txt
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.29 (Ubuntu) Server at **.**.** Port 443
```

Apache logs says:
```txt
[Sun Nov 14 18:26:28.411592 2021] [proxy:error] [pid 20983:tid 139907435534080] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:3000 (127.0.0.1) failed
[Sun Nov 14 18:26:28.411648 2021] [proxy_http:error] [pid 20983:tid 139907435534080] [client 37.165.58.104:12652] AH01114: HTTP: failed to make connection to backend: 127.0.0.1
```

Systemctl says:

```txt
● mailtrain.service - Mailtrain server
   Loaded: loaded (/etc/systemd/system/mailtrain.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2021-11-14 18:40:26 UTC; 4s ago
  Process: 23884 ExecStart=/usr/bin/node index.js (code=exited, status=1/FAILURE)
 Main PID: 23884 (code=exited, status=1/FAILURE)
```

Mailtrain says:

```txt
-- Logs begin at Fri 2021-10-01 05:03:51 UTC, end at Sun 2021-11-14 18:45:27 UTC. --
Nov 14 18:29:01 vps-81a9f6ec systemd[1]: Started Mailtrain server.
Nov 14 18:29:04 vps-81a9f6ec node[21938]: info Using local auth
Nov 14 18:29:04 vps-81a9f6ec node[21938]: info sql SQL not set up, initializing
Nov 14 18:29:04 vps-81a9f6ec node[21938]: info sql Loading tables from mailtrain.sql
Nov 14 18:29:06 vps-81a9f6ec node[21938]: info sql Database check completed
Nov 14 18:29:07 vps-81a9f6ec node[21938]: migration file "20200824160149_convert_to_utf8mb4.js" failed
Nov 14 18:29:07 vps-81a9f6ec node[21938]: migration failed with error: ALTER TABLE blacklist CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE campaign_links CONVERT TO CHARACTER SE
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR! Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Query.Sequence._packetToError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Query.ErrorPacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Protocol._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Parser._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Parser.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Protocol.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:91:28)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Socket.emit (events.js:400:28)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Socket.emit (domain.js:475:12)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at addChunk (internal/streams/readable.js:293:12)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at readableAddChunk (internal/streams/readable.js:267:9)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Socket.Readable.push (internal/streams/readable.js:206:10)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     --------------------
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Protocol._enqueue (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Connection.query (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:201:25)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Promise._execute (/opt/mailtrain/server/node_modules/bluebird/js/release/debuggability.js:384:9)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Promise._resolveFromExecutor (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:518:18)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at new Promise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:103:10)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Client_MySQL._query (/opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Client_MySQL.query (/opt/mailtrain/server/node_modules/knex/lib/client.js:192:17)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/transaction.js:232:21
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Function.Promise.attempt.Promise.try (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:39:29)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Client_MySQL.trxClient.query (/opt/mailtrain/server/node_modules/knex/lib/transaction.js:229:33)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Runner.<anonymous> (/opt/mailtrain/server/node_modules/knex/lib/runner.js:138:36)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Runner.tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Runner.query (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:15:34)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/runner.js:47:21
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at /opt/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Promise._settlePromiseFromHandler (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:547:31)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Promise._settlePromise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:604:18)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Promise._settlePromise0 (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!  Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Query.Sequence._packetToError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Query.ErrorPacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Protocol._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Parser._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Parser.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Protocol.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Nov 14 18:29:07 vps-81a9f6ec node[21938]: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:91:28)
```

Does someone reproduce this?

Thanks for the help!

**Comment by Terminator81** [comment]
@RomainFallet 
maybe this: #1110

**Comment by RomainFallet** [comment]
@Terminator81 Thanks, this solves the issue. If this is a problem with a Mariadb version, maybe the install script should install another version or apply the fix above directly. What do you think ?
