### ISSUE TITLE
Getting error "gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/mailtrain/client/node_modules/node-sass/.node-gyp'" while installing mailtrain setup on fresh Debien 10

### ISSUE THREAD

**Issue by Ranjithkumarreddy12** [Mailtrain-org/mailtrain#1168]
> node-sass@4.14.1 install /opt/mailtrain/client/node_modules/node-sass
> node scripts/install.js

Unable to save binary /opt/mailtrain/client/node_modules/node-sass/vendor/linux-x64-83 : Error: EACCES: permission denied, mkdir '/opt/mailtrain/client/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:1013:3)
    at sync (/opt/mailtrain/client/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/opt/mailtrain/client/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/opt/mailtrain/client/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/opt/mailtrain/client/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/opt/mailtrain/client/node_modules/node-sass/vendor'
}

> core-js@3.4.7 postinstall /opt/mailtrain/client/node_modules/@coreui/coreui/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> @coreui/coreui@2.1.16 postinstall /opt/mailtrain/client/node_modules/@coreui/coreui
> coreui-plugin-npm-postinstall || exit 0

Thank you for using free version of CoreUI!
CoreUI is an MIT licensed open source project and completely free to use. However, the amount of effort needed to maintain and develop new features for the project is not sustainable without proper financial backing. You can support development by buying CoreUI Pro Version: https://coreui.io/pro/

> @fortawesome/fontawesome-free@5.15.3 postinstall /opt/mailtrain/client/node_modules/@fortawesome/fontawesome-free
> node attribution.js

Font Awesome Free 5.15.3 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

> node-sass@4.14.1 postinstall /opt/mailtrain/client/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /opt/mailtrain/client/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/opt/mailtrain/client/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.18.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.18.2
gyp verb command install [ '14.18.2' ]
gyp verb install input version string "14.18.2"
gyp verb install installing version: 14.18.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/14.18.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/mailtrain/client/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '14.18.2' ]
gyp verb install input version string "14.18.2"
gyp verb install installing version: 14.18.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 14.18.2
gyp verb ensuring nodedir is created /opt/mailtrain/client/node_modules/node-sass/.node-gyp/14.18.2
gyp WARN install got an error, rolling back install
gyp verb command remove [ '14.18.2' ]
gyp verb remove using node-gyp dir: /opt/mailtrain/client/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 14.18.2
gyp verb remove removing development files for version: 14.18.2
gyp WARN install got an error, rolling back install
gyp verb command remove [ '14.18.2' ]
gyp verb remove using node-gyp dir: /opt/mailtrain/client/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 14.18.2
gyp verb remove removing development files for version: 14.18.2
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/mailtrain/client/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.19.0-11-cloud-amd64
gyp ERR! command "/usr/bin/node" "/opt/mailtrain/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/mailtrain/client/node_modules/node-sass
gyp ERR! node -v v14.18.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/@babel/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-07T13_45_45_705Z-debug.log
root@ip-x-x-x-x:/opt/mailtrain#

**Comment by Ranjithkumarreddy12** [comment]
This issue is resolved by edidted file `setup/functions` line number 296 by adding `--unsafe-perm` at the end of the line.
