### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: read ECONNRESET when creating an import

### ISSUE THREAD

**Issue by sandoche** [Mailtrain-org/mailtrain#1187]
When I create an import I get this error in the logs:
```

2022-01-11T18:00:09.102131593Z (node:102) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
2022-01-11T18:00:09.102166082Z     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
2022-01-11T18:00:09.102173691Z     --------------------
2022-01-11T18:00:09.102179820Z     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2022-01-11T18:00:09.102185957Z     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
2022-01-11T18:00:09.102191887Z     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
2022-01-11T18:00:09.102197771Z     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)
2022-01-11T18:00:09.102203660Z     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)
2022-01-11T18:00:09.102209545Z     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)
2022-01-11T18:00:09.102215318Z     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
2022-01-11T18:00:09.102221195Z     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
2022-01-11T18:00:09.102227035Z     at /app/server/node_modules/knex/lib/transaction.js:232:21
2022-01-11T18:00:09.102232695Z     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
2022-01-11T18:00:09.102238391Z     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
2022-01-11T18:00:09.102246417Z     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
2022-01-11T18:00:09.102260270Z     at Transaction_MySQL.query (/app/server/node_modules/knex/lib/dialects/mysql/transaction.js:23:30)
2022-01-11T18:00:09.102304922Z     at Transaction_MySQL.begin (/app/server/node_modules/knex/lib/transaction.js:86:17)
2022-01-11T18:00:09.102313910Z     at Transaction._promise._bluebird.default.using.connection (/app/server/node_modules/knex/lib/transaction.js:38:75)
2022-01-11T18:00:09.102321878Z     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
2022-01-11T18:00:09.102328580Z     at /app/server/node_modules/bluebird/js/release/using.js:185:26
2022-01-11T18:00:09.102333442Z     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
2022-01-11T18:00:09.102338320Z     at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:547:31)
2022-01-11T18:00:09.102343165Z     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:604:18)
2022-01-11T18:00:09.102347956Z     at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:649:10)
2022-01-11T18:00:09.102354297Z     at Promise._settlePromises (/app/server/node_modules/bluebird/js/release/promise.js:729:18)
2022-01-11T18:00:09.102697746Z (node:102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2022-01-11T18:00:09.102795060Z (node:102) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The page doesn't say anything else than:
"Preparation in progress. Please wait till it is done or visit this page later."

Then nothing happens.

If I try again with the same file or another file, I don't get any error again, but still the page shows the same and I don't see any error.

**Comment by sandoche** [comment]
After restarting the server the page works again.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
