### ISSUE TITLE
toISOString error

### ISSUE THREAD

**Issue by anwarHN** [Mailtrain-org/mailtrain#134]
I´m having this error:

TypeError: row.created.toISOString is not a function
    at C:\nodejsprojects\mailtrain\routes\campaigns.js:329:70
    at Array.map (native)
    at C:\nodejsprojects\mailtrain\routes\campaigns.js:324:24
    at Query._callback (C:\nodejsprojects\mailtrain\lib\models\campaigns.js:108:32)
    at Query.Sequence.end (C:\nodejsprojects\mailtrain\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\nodejsprojects\mailtrain\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.EofPacket (C:\nodejsprojects\mailtrain\node_modules\mysql\lib\protocol\sequences\Query.js:121:8)
    at Protocol._parsePacket (C:\nodejsprojects\mailtrain\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\nodejsprojects\mailtrain\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (C:\nodejsprojects\mailtrain\node_modules\mysql\lib\protocol\Protocol.js:39:16)

Can you help me?

**Comment by witzig** [comment]
@anwarHN, I assume you solved this problem by now? Please feel free to open this issue again if that's not the case.
