### ISSUE TITLE
CAS not working in docker

### ISSUE THREAD

**Issue by JohanBraeken** [Mailtrain-org/mailtrain#1365]
When enabling CAS support in a docker instance of mailtrain, it tries to install "passport-cas2" upon start.
This fails with the following boot messages:

```
Info: Generating application/production.yaml
Info: LDAP not enabled
Info: CAS enabled
Info: Generating server/production.yaml
Info: Waiting for MySQL Server
Info: Waiting for Redis Server
Info: Installing passport-cas2
npm ERR! code ENOENT
m ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/joshchan/node-cas.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-10-31T19_39_52_851Z-debug.log
```

Partial contents of debug file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'passport-cas2' ]
2 info using npm@6.14.12
3 info using node@v10.24.1
4 verbose npm-session 05189266f511dae4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/passport-cas2 179ms
8 http fetch GET 200 https://registry.npmjs.org/passport-cas2/-/passport-cas2-0.0.12.tgz 66ms
9 silly pacote tag manifest for passport-cas2@latest fetched in 254ms
10 timing stage:loadCurrentTree Completed in 1477ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 13ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 730ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule passport-cas2@0.0.12 checking installable status
18 silly removeObsoleteDep removing passport-cas2@0.0.11 from the tree as its been replaced by a newer version or is no longer required
19 silly removeObsoleteDep removing cas@git://github.com/joshchan/node-cas.git#344a8bfba9d054e2e378adaf95b720c898ae48a2 from the tree as its been replaced by a newer version or is no longer required
20 silly removeObsoleteDep removing cheerio@0.19.0 from the tree as its been replaced by a newer version or is no longer required
21 silly removeObsoleteDep removing css-select@1.0.0 from the tree as its been replaced by a newer version or is no longer required
22 silly removeObsoleteDep removing css-what@1.0.0 from the tree as its been replaced by a newer version or is no longer required
23 silly removeObsoleteDep removing domutils@1.4.3 from the tree as its been replaced by a newer version or is no longer required
24 silly removeObsoleteDep removing htmlparser2@3.8.3 from the tree as its been replaced by a newer version or is no longer required
25 silly removeObsoleteDep removing domhandler@2.3.0 from the tree as its been replaced by a newer version or is no longer required
26 silly removeObsoleteDep removing domutils@1.5.1 from the tree as its been replaced by a newer version or is no longer required
27 silly removeObsoleteDep removing entities@1.0.0 from the tree as its been replaced by a newer version or is no longer required
28 silly removeObsoleteDep removing readable-stream@1.1.14 from the tree as its been replaced by a newer version or is no longer required
29 silly removeObsoleteDep removing isarray@0.0.1 from the tree as its been replaced by a newer version or is no longer required
30 silly removeObsoleteDep removing string_decoder@0.10.31 from the tree as its been replaced by a newer version or is no longer required
31 silly removeObsoleteDep removing lodash@3.10.1 from the tree as its been replaced by a newer version or is no longer required
32 silly fetchPackageMetaData error for cas@git+https://github.com/joshchan/node-cas.git Error while executing:
32 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/joshchan/node-cas.git
32 silly fetchPackageMetaData
32 silly fetchPackageMetaData
32 silly fetchPackageMetaData spawn git ENOENT
33 timing stage:rollbackFailedOptional Completed in 3ms
34 timing stage:runTopLevelLifecycles Completed in 2247ms
35 silly saveTree mailtrain@2.0.0
35 silly saveTree +-- aws-sdk@2.601.0
35 silly saveTree | +-- buffer@4.9.1
35 silly saveTree | | +-- base64-js@1.3.0
35 silly saveTree | | +-- ieee754@1.1.8
35 silly saveTree | | `-- isarray@1.0.0
35 silly saveTree | +-- events@1.1.1
35 silly saveTree | +-- ieee754@1.1.13
35 silly saveTree | +-- jmespath@0.15.0
35 silly saveTree | +-- querystring@0.2.0
35 silly saveTree | +-- sax@1.2.1
35 silly saveTree | +-- url@0.10.3
35 silly saveTree | | `-- punycode@1.3.2
...
35 silly saveTree +-- smtp-server@3.5.0
35 silly saveTree | +-- base32.js@0.1.0
35 silly saveTree | +-- ipv6-normalize@1.0.1
35 silly saveTree | `-- nodemailer@5.0.0
35 silly saveTree +-- tmp-promise@1.1.0
35 silly saveTree | `-- tmp@0.1.0
35 silly saveTree |   `-- rimraf@2.6.3
35 silly saveTree +-- toml@2.3.6
35 silly saveTree +-- try-require@1.2.1
35 silly saveTree +-- url-pattern@1.0.3
35 silly saveTree `-- xmldom@0.1.31
36 verbose stack Error: spawn git ENOENT
36 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
36 verbose stack     at onErrorNT (internal/child_process.js:415:16)
36 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
37 verbose cwd /app/server
38 verbose Linux 5.4.0-164-generic
39 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "passport-cas2"
40 verbose node v10.24.1
41 verbose npm  v6.14.12
42 error code ENOENT
43 error syscall spawn git
44 error path git
45 error errno ENOENT
46 error enoent Error while executing:
46 error enoent undefined ls-remote -h -t https://github.com/joshchan/node-cas.git
46 error enoent
46 error enoent
46 error enoent spawn git ENOENT
47 error enoent This is related to npm not being able to find a file.
48 verbose exit [ 1, true ]
```

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
