### ISSUE TITLE
Mailtrain v3 - Development

### ISSUE THREAD

**Issue by forgeOneHQ** [Mailtrain-org/mailtrain#1372]
We are going to start the development of Mailtrain V3.

Mailtrain v3 is focusing on the stability and updating all libraries to the latest versions.

ToDo:

- [x] Update Mailtrain libraries to latest version
- [ ] Testing v3
- [ ] Write user and developer documentation for Maitrain v3

Feature Requests are collected in this issue: #1373

**Comment by fthobe** [comment]
Hey, I really appreciate the effort and would totally be up to sponsor features with my company giving development resources as I am infinitely sick and tired of mailchimp. Is there a feature list you plan to include? I saw all feature requests and bug reports have been closed, what's the new roadmap here?

**Comment by forgeOneHQ** [comment]
@fthobe the list above will be adopted. 

We initialize start to prepare the base to get all up to date and write the documentation so it is easier for developers starting with development for mailtrain. 

We also plan to move to containers. OS packages maybe later. But to speed up the development containers are easier.

**Comment by fthobe** [comment]
So v3 will be an intermediate step basically adjusting some architecture and update libraries, correct?

**Comment by bures** [comment]
It would help us to know what features are essential for you. We would like to make Mailtrain a bit leaner in order to simplify it's maintenance. As the result, we would like to drop some functionality that probably no one ever used (such as Reports). In order not to remove stuff that is used, we would like to know which Mailtrain features our community uses (like LDAP, automation = triggered campaigns, RSS campaigns, list segmentation, GrapeJS, API - which functions).

**Comment by fthobe** [comment]
If you share some details I can contribute a full time developer for 2-4 weeks, but there must be a tangible outcome for us -> kill of mailchimp by integrating abandoned cart and purchase based triggers, if we on the way close your bucket list as well I am perfectly happy with that.

**Comment by bures** [comment]
@fthobe, can you create a separate ticket for the functionality you mentioned and describe it there in a bit more detail? If your developer know his/her business, I would be happy to supervise this effort a bit a then bring the functionality in. I just would like to see first, how it fits in. If it fits, I would let you know once Mailtrain v3 will be in a shape when contributions would be sensible.

**Comment by forgeOneHQ** [comment]
@fthobe we can make an issue for feature requests to collect them for v3.

I can make one but the want to get mailtrain up to date first.

Two things I imagine is ldap / sso and 2FA.

**Comment by fthobe** [comment]
> can you create a separate ticket for the functionality you mentioned and describe it there in a bit more detail? 
>
>

Issue #1000 was testing the water and never received response ;) If the ticket is reopened I can elaborate and expand it. 

>If your developer know his/her business, I would be happy to supervise this effort a bit a then bring the functionality in.
>
>

We do have some capable people;)

>I just would like to see first, how it fits in. If it fits, I would let you know once Mailtrain v3 will be in a shape when contributions would be sensible.
> 
> 

I totally agree that features that go beyond basic newsletter templates should remain a modular component. 

We would like to make Mailtrain a bit leaner in order to simplify it's maintenance. As the result, we would like to drop some functionality that probably no one ever used (such as Reports). In order not to remove stuff that is used, we would like to know which Mailtrain features our community uses (like LDAP, automation = triggered campaigns, RSS campaigns, list segmentation, GrapeJS, API - which functions).
> 
> 

We do have capable people ;)

I think LDAP while a great technology, in times of Microsoft Entra and google workspace is becoming more and more redundant. Also considering the effort that now needs to put into Microsoft on premise installations to keep it running (certificates mostly). 

Removing reports and segments would reduce mailtrain to an smtp frontend / mail editor, I just believe to get this thing to take off the approach should be more relevant for commercial use to result also in significant community contributions. I think there is a real case to be made (also communication wise) to establish an alternative to existing mass mail platforms. 

I will find some time tomorrow to open up and create issues. Is there a demo running somewhere?

**Comment by forgeOneHQ** [comment]
@fthobe let me create a new issue to collect the ideas :) 

For PKI / Certificates I use freeipa  or any other pki solution. MS is not dependable but thats because I implement wherever I can linux open source based solutions instead of proprietary software.

**Comment by forgeOneHQ** [comment]
Feature Requests are collected here: #1373

**Comment by caloon** [comment]
Is v3 development still ongoing? The last comment on this thread was three months ago. I just tried to deploy Mailtrain on a new server, but since most VPS providers do no longer offer Ubuntu 18.04, Node.js 14, etc. it can't be (re-)installed right now.

**Comment by forgeOneHQ** [comment]
@caloon yes, the situation that it relies on @bures at the moment. We are communicating but it is slow at the moment.

I hope that with v3 we can implement development guides to speed it up :)

**Comment by fillon** [comment]
I am in the same situation, our provider no longer offer Nodejs14...
@talheim-it do you have a rough date for v3, is it for this month, 6 months.... 
Just to get an idea if we wait to build our server or move to another solution
tx

**Comment by forgeOneHQ** [comment]
@fillon thanks for your feedback.

I wrote @bures  about it to make the process more transparent.

I completely agree that the silence here makes it abandoned and we need to improve the communication.

I will try to give you an update in approx a week :)

**Comment by fillon** [comment]
Thanks @talheim-it :)

**Comment by rastarr** [comment]
@talheim-it Also wondering the state of things.
any update?

**Comment by forgeOneHQ** [comment]
@fillon @rastarr I was waiting for the feedback from @bures.

The situation is that only @bures is working at the moment on mailtrain. So he works on mailtrain whenever he finds a time for it. Approximate time is planned for end of 2024. 

I don't have better news for the moment but on my end I really pushing to work on a documentation not just to use mailtrain but also how to develop to increase the community so that not all relies on @bures.

I try to stay in touch with @bures and do my "community job" here to give you updates.

Whenever you have questions do not hesitate to ask.

**Comment by forgeOneHQ** [comment]
@fillon @rastarr  and for everyone else.

We have an update.

@bures prepared a v3 we are going to start testing. The main focus is to see if everything is working. We are down to the core features to get a stable base from where we can start the documentation and implementation with PRs.

**Comment by forgeOneHQ** [comment]
Testing is in progress.

**Comment by leegang** [comment]
A/B testing

**Comment by donatid** [comment]
Hi @talheim-it any update on the test?

**Comment by ganeshkrishnan1** [comment]
do you need any devs? Our team can sponsor an hour or so everyday to help speed this up

**Comment by dgulias** [comment]
I'm here to support anyway as well. Let's go!

**Comment by dgulias** [comment]
Hello my friends, how is going the V3? Is about to be released or far from it? 

Today I reinstalled the Mailtrain into a Debian10 system and I had a lot of things to make it to work (lots of things deprecated).

**MINI TUTORIAL:**

Main changes I had to fix (before and after the Mailtrain install):

### Before the Mailtrain install:

**1) Update Debian10 source list**

Debian10 - changed source list mirrors - how to fix:
Source: https://debiansupport.com/mirrors/

Where: /etc/apt/sources.list

change to:
```
deb http://archive.debian.org/debian/ buster main contrib non-free
deb http://archive.debian.org/debian/ buster-proposed-updates main contrib non-free
deb http://archive.debian.org/debian-security buster/updates main contrib non-free
```



**2) Update MariaDB before**

Update MariaDB before install the Mailtrain (the Mailtrain version is too much deprecated)

Commands:
```
sudo apt update
sudo apt install mariadb-server
```



**3) Install Mailtrain without update Node/NPM before**

Install without update anything (Node, NPM, etc.). 
I deleted / purged every existent version of Node/NPM before.

---

Do all the common Mailtrain pre-setup procedures (subdomains, DNS, hostname, etc.)
**INSTALL MAILTRAIN**
Login on the platform with admin:test - as soon  as possible
Change admin username and password - as soon  as possible

---

### After the Mailtrain install

**1) Secure Mysql/Mariadb**

`sudo mysql_secure_installation`
(follow steps according your needs and add password for root user)



**2) Update NPM manually and Node.JS using NVM manager**

**Update NPM:**

`npm install -g npm`


**Install NVM to update Node.JS:**

```
#Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

#in lieu of restarting the shell
\. "$HOME/.nvm/nvm.sh"

#Download and install Node.js:
nvm install 24 # version to date of this post. 

#Verify the Node.js version:
node -v # Should print "v24.11.1" - version to date of this post. 

#Verify npm version:
npm -v # Should print "11.6.2" - version to date of this post.
```



**3) Fix / Audit NPM modules**
Fix NPM apps/modules installations inside Mailtrain

Inside /opt/mailtrain 

```
npm cache clean --force
npm audit fix --force
```



**4) Remove "innodb_file_format" because it breaks MariaDB after 10.2 version**
Remove (comment out) the line "innodb_file_format=*****" in both files (bellow) because the option "innodb_file_format" has been removed in mariadb 10.3, and barracuda is now the default value :

/etc/mysql/my.cnf
(by default is coming without it, but if is there just comment it out)

/etc/mysql/mariadb.conf.d/60-fix-key-length.cnf

```
[mysqld]
#innodb_file_format = Barracuda
innodb_file_per_table = on
innodb_default_row_format = dynamic
innodb_large_prefix = 1
#innodb_file_format_max = Barracuda
```



**5) Fix Upload Image Issue or Delete campaign issue**

To fix errors like the bellow when uploading images:
"EACCES: permission denied, open '/opt/mailtrain/server/files/uploaded/***'" 
*INTERNAL SERVER ERROR - When upload image:

There are 3 options:

1 - Less safe in my point of view:

`sudo chmod -R 775 /opt/mailtrain`


2 - More Safe option (best option in my pinion):

`sudo chown -R mailtrain:mailtrain /opt/mailtrain`


3 - This option can work as an alternative when the other options doesn't work:

Using Filezilla, put directly permission 777 (+ recursive) into the /mailtrain/server/files

**Comment by bures** [comment]
The problem with v3 is that some of the libraries we depended are not supported any more and there is no good replacement. At this moment, the biggest headache is the tree editor for segments. The nice library for rearranging data in the tree structure does not work with the recent react. So I'll replace it with simple text area into which one will write an expression which specifies the segment filter. It's quite regression, but I couldn't figure out better alternative.

In the same way, I already had to replace the client router, because the react router completely rehauls its API with every release. The last one does not work with react classes.

Sorry it takes so long. But I have other priorities. Unfortunately, the whole ecosystem we depend on moves a bit too fast.

**Comment by bures** [comment]
My aim is to use some of the Christmas period to do these changes and to finally have a release of v3 that can work with current installations.

**Comment by dgulias** [comment]
Thank you for all your effort.

With the tutorial I showed above I can make Mailtrain to works fine into a Debian10 OS.

Now I'm only having a difficult to make "View on browser" [LINK_BROWSER] to work. I don't know if this piece was abandon or not.

With {{LINK_BROWSER}} I got a better results (link works) but send to a wrong page. I didn't find a direct question about it, I i wanted to know if this is a abandon code in level of development, or if I just need to change it somehow.

**Comment by bures** [comment]
If you specify template language as "Simple" then you should use "[LINK_BROWSER]". If you specify it to be "Handlebars" then you should use "{{LINK_BROWSER}}"

**Comment by dgulias** [comment]
I'll create a topic about it, because for some reason when we use "Predefinide template" it came stuck without the "remove sponsor" options and the links (Unsubscribe )doesn't work for me.

Only works when i make a Copy of the "Default Mosaico Template" and use as base for Simple and Handlebars "Mosaico Template" (changing [ ] with {{ }} ) but still getting some issues.

**Comment by lustsazeus-lab** [comment]
For v3 stabilization, a low-risk sequencing is: lock one CI smoke matrix first (Node/DB variants), then document upgrade/migration notes while testing runs.\n\nIf useful, I can help draft a minimal test checklist + migration doc skeleton so contributors can parallelize without drift.

**Comment by TJMdeveloper** [comment]
Is this project still being worked on?  does it work?  I cloned it and built (on windows 11).  When I try to start the **server** I am getting this error:

npm start

> mailtrain@3.0.0 start
> node index.js

node:internal/buffer:961
    super(bufferOrLength, byteOffset, length);
    ^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (node:internal/buffer:961:5)
    at Function.alloc (node:buffer:400:10)
    at preload6 (c:\projectspace\git-local\mailtrain\server\node_modules\geoip-lite\lib\geoip.js:445:30)      
    at Object.<anonymous> (c:\projectspace\git-local\mailtrain\server\node_modules\geoip-lite\lib\geoip.js:536:1)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)

Node.js v22.14.0
PS c:\projectspace\git-local\mailtrain\server> 

I also had to add start script to package.json in server folder since its not there... maybe that is why its not working?

I can help a bit trying to get it setup and reporting feedback and making some fixes.  Just wondering if the project is still being maintained and v3 is in a working state? or maybe its not ready yet?

TJ
