### ISSUE TITLE
Widgets and custom forms cause Mailtrain to crash

### ISSUE THREAD

**Issue by jloh** [Mailtrain-org/mailtrain#201]
I tried setting up widgets and it kept crashing, finally managed to get an error out of it:

```
/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:79
         throw err; // Rethrow non-MySQL errors
         ^
 TypeError: Cannot set property 'template' of undefined
     at forms.get (/opt/mailtrain/lib/helpers.js:159:32)
     at Query.connection.query [as _callback] (/opt/mailtrain/lib/models/forms.js:93:24)
     at Query.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
     at Query._handleFinalResultPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
     at Query.EofPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:121:8)
     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:280:23)
     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:75:12)
     at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:39:16)
     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:103:28)
     at emitOne (events.js:96:13)
```

After changing the custom form back to the default one the error stopped and Mailtrain served the `widget.js` file fine without crashing.

**Comment by witzig** [comment]
A fix is in master now. Thanks!

**Comment by jloh** [comment]
Thanks, looks good now!
