### ISSUE TITLE
Configure zone-mta to use with SSL

### ISSUE THREAD

**Issue by afanjul** [Mailtrain-org/mailtrain#210]
Hi again, guys, I'm trying to setup my server as secure as I can, I've got a STARTTLS connection successfully but i would like to get SSL capable smtp (and there is no way to get it). This is my actual config:

```
"feeder": {
            "enabled": true,
            "port": 555, //custom port to avoid standard scanners
            "processes": 2,
            "host": "mailtrain.xxxxx.com",
            "authentication": true,
            "starttls": true,
            //"secure": true, //if we comment out, the smtp doesnt connect and fails
            "key": "/etc/letsencrypt/live/mailtrain.xxxxxx.com/privkey.pem",
            "cert": "/etc/letsencrypt/live/mailtrain.xxxxxx.com/fullchain.pem"
        }
```

I have successfuly installed the letsencrypt certificate and it seems to catch it. But anytime we commentout secure (to true) it fails...

I've got this error in zone-mta.log

```
TypeError: this._socket.getCipher is not a function
    at new SMTPConnection (/opt/zone-mta/node_modules/smtp-server/lib/smtp-connection.js:65:50)
    at SMTPServer.connect (/opt/zone-mta/node_modules/smtp-server/lib/smtp-server.js:95:22)
    at process.on.E (/opt/zone-mta/receiver.js:126:27)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:753:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: 140227671897984:error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_srvr.c:640:

    at Error (native)
```

My specs:
-Linux mailtrain.xxxxxx.com 4.4.0-72-generic #93~14.04.1-Ubuntu SMP Fri Mar 31 15:05:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-OpenSSL 1.0.1f 6 Jan 2014

Any suggestion? thanks

**Comment by andris9** [comment]
TLS with secure:true is broken in ZoneMTA for now. STARTTLS should be just as fine as the only difference between STARTTLS and TLS is when the connection is upgraded to TLS.

**Comment by afanjul** [comment]
Thanks for your info @andris9 !
