### ISSUE TITLE
We are getting Mail Error: Mail command failed: 503 EHLO/HELO first please

### ISSUE THREAD

**Issue by afanjul** [Mailtrain-org/mailtrain#248]
Hi @andris9 sometimes we are getting this errors when sending a campaign, mostly it appears the second time we send a campaign, do you have any clue about this to look further?

```
ERR! Mail Error: Mail command failed: 503 EHLO/HELO first please
ERR! Mail     at SMTPConnection._formatError (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:557:19)
ERR! Mail     at SMTPConnection._actionMAIL (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:1274:34)
ERR! Mail     at SMTPConnection._responseActions.push.str (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:796:18)
ERR! Mail     at SMTPConnection._processResponse (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:706:20)
ERR! Mail     at SMTPConnection._onData (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:509:14)
ERR! Mail     at Socket._socket.on.chunk (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:461:47)
ERR! Mail     at emitOne (events.js:96:13)
ERR! Mail     at Socket.emit (events.js:188:7)
ERR! Mail     at readableAddChunk (_stream_readable.js:176:18)
ERR! Mail     at Socket.Readable.push (_stream_readable.js:134:10)
ERR! Mail  { Error: Mail command failed: 503 EHLO/HELO first please
ERR! Mail     at SMTPConnection._formatError (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:557:19)
ERR! Mail     at SMTPConnection._actionMAIL (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:1274:34)
ERR! Mail     at SMTPConnection._responseActions.push.str (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:796:18)
ERR! Mail     at SMTPConnection._processResponse (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:706:20)
ERR! Mail     at SMTPConnection._onData (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:509:14)
ERR! Mail     at Socket._socket.on.chunk (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:461:47)
ERR! Mail     at emitOne (events.js:96:13)
ERR! Mail     at Socket.emit (events.js:188:7)
ERR! Mail     at readableAddChunk (_stream_readable.js:176:18)
ERR! Mail     at Socket.Readable.push (_stream_readable.js:134:10)
ERR! Mail   code: 'EENVELOPE',
ERR! Mail   response: '503 EHLO/HELO first please',
ERR! Mail   responseCode: 503,
ERR! Mail   command: 'MAIL FROM' }
ERR! Subscription Error: Mail command failed: 503 EHLO/HELO first please
ERR! Subscription     at SMTPConnection._formatError (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:557:19)
ERR! Subscription     at SMTPConnection._actionMAIL (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:1274:34)
ERR! Subscription     at SMTPConnection._responseActions.push.str (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:796:18)
ERR! Subscription     at SMTPConnection._processResponse (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:706:20)
ERR! Subscription     at SMTPConnection._onData (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:509:14)
ERR! Subscription     at Socket._socket.on.chunk (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:461:47)
ERR! Subscription     at emitOne (events.js:96:13)
ERR! Subscription     at Socket.emit (events.js:188:7)
ERR! Subscription     at readableAddChunk (_stream_readable.js:176:18)
ERR! Subscription     at Socket.Readable.push (_stream_readable.js:134:10)
ERR! Subscription  { Error: Mail command failed: 503 EHLO/HELO first please
ERR! Subscription     at SMTPConnection._formatError (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:557:19)
ERR! Subscription     at SMTPConnection._actionMAIL (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:1274:34)
ERR! Subscription     at SMTPConnection._responseActions.push.str (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:796:18)
ERR! Subscription     at SMTPConnection._processResponse (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:706:20)
ERR! Subscription     at SMTPConnection._onData (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:509:14)
ERR! Subscription     at Socket._socket.on.chunk (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:461:47)
ERR! Subscription     at emitOne (events.js:96:13)
ERR! Subscription     at Socket.emit (events.js:188:7)
ERR! Subscription     at readableAddChunk (_stream_readable.js:176:18)
ERR! Subscription     at Socket.Readable.push (_stream_readable.js:134:10)
ERR! Subscription   code: 'EENVELOPE',
ERR! Subscription   response: '503 EHLO/HELO first please',
ERR! Subscription   responseCode: 503,
ERR! Subscription   command: 'MAIL FROM' }
```

**Comment by witzig** [comment]
Searching for "503 EHLO/HELO first please" on GitHub yields 3 results. Are you by chance using Postal? See here: https://github.com/atech/postal/issues/151

**Comment by andris9** [comment]
Seems like a problem on the SMTP server end to me too.

**Comment by afanjul** [comment]
Yeah, thanks I was thinking that it was a mailtrain issue but actually is from the postal side ^_^, you can close it...
