### ISSUE TITLE
405 on URL based template

### ISSUE THREAD

**Issue by manjeshpv** [Mailtrain-org/mailtrain#313]
When I'm trying to send a campaign through URL

Received status code 405 from https://www.quezx.com/
```sh
: ERR! Mail Error: Received status code 405 from https://www.quezx.com/
: ERR! Mail     at Request.request.post [as _callback] (/opt/mailtrain/services/sender.js:449:49)
: ERR! Mail     at Request.self.callback (/opt/mailtrain/node_modules/request/request.js:188:22)
: ERR! Mail     at emitTwo (events.js:106:13)
: ERR! Mail     at Request.emit (events.js:194:7)
: ERR! Mail     at Request.<anonymous> (/opt/mailtrain/node_modules/request/request.js:1171:10)
: ERR! Mail     at emitOne (events.js:96:13)
: ERR! Mail     at Request.emit (events.js:191:7)
: ERR! Mail     at IncomingMessage.<anonymous> (/opt/mailtrain/node_modules/request/request.js:1091:12)
: ERR! Mail     at Object.onceWrapper (events.js:293:19)
: ERR! Mail     at emitNone (events.js:91:20)
: ERR! Mail Error: Received status code 405 from https://cdn.quezx.com/mailers/qdirect-accept-reject-force/index.html
: ERR! Mail     at Request.request.post [as _callback] (/opt/mailtrain/services/sender.js:449:49)
: ERR! Mail     at Request.self.callback (/opt/mailtrain/node_modules/request/request.js:188:22)
: ERR! Mail     at emitTwo (events.js:106:13)
: ERR! Mail     at Request.emit (events.js:194:7)
: ERR! Mail     at Request.<anonymous> (/opt/mailtrain/node_modules/request/request.js:1171:10)
: ERR! Mail     at emitOne (events.js:96:13)
: ERR! Mail     at Request.emit (events.js:191:7)
: ERR! Mail     at IncomingMessage.<anonymous> (/opt/mailtrain/node_modules/request/request.js:1091:12)
: ERR! Mail     at Object.onceWrapper (events.js:293:19)
: ERR! Mail     at emitNone (events.js:91:20)

```

**Comment by witzig** [comment]
The URL will be POSTed to using Merge Tags as POST body, which is not allowed by your server.

**Comment by manjeshpv** [comment]
@witzig  So then how can i send mails in static cdn server

**Comment by andris9** [comment]
If the content is static then why do you need to send through external URL's? Use the template code editor and copy your message content into the template.
