### ISSUE TITLE
Mailtrain Crashes when importing List

### ISSUE THREAD

**Issue by jonathangilpin** [Mailtrain-org/mailtrain#324]
This is a fresh install of mailtrain. I have created several custom fields on a list called text and then tried to import the list.

[root@emailer /home/mailtrain]# npm i -g npm 
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.4.2
added 21 packages, removed 22 packages and updated 19 packages in 7.92s
[root@emailer /home/mailtrain]# NODE_ENV=production npm start

> mailtrain@1.23.2 start /usr/home/mailtrain
> node index.js

info Using local auth 
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
info sql Database check completed
info Express WWW server listening on port 3000
verb UTC Updating timezone offsets
info Service All services started
info HTTP GET /lists/view/1 302 13.416 ms - 118
info HTTP GET /users/login?next=%2Flists%2Fview%2F1 200 66.303 ms - -
info HTTP GET /bootstrap/themes/united.min.css 304 1.275 ms - -
info HTTP GET /datatables/datatables.min.css 304 0.746 ms - -
info HTTP GET /datepicker/css/bootstrap-datepicker3.css 304 1.062 ms - -
info HTTP GET /css/footer.css 304 0.224 ms - -
info HTTP GET /css/mailtrain.css 304 0.196 ms - -
info HTTP GET /javascript/jquery-2.2.1.min.js 304 0.533 ms - -
info HTTP GET /bootstrap/js/bootstrap.min.js 304 0.821 ms - -
info HTTP GET /datatables/datatables.min.js 304 0.768 ms - -
info HTTP GET /datepicker/js/bootstrap-datepicker.min.js 304 1.111 ms - -
info HTTP GET /javascript/tables.js 304 1.407 ms - -
info HTTP GET /moment/moment.min.js 304 1.701 ms - -
info HTTP GET /javascript/fetch.js 304 0.212 ms - -
info HTTP POST /users/login 302 212.583 ms - 70
info HTTP GET /lists/view/1 200 55.518 ms - -
info HTTP GET /bootstrap/themes/united.min.css 304 0.268 ms - -
info HTTP GET /datatables/datatables.min.css 304 0.584 ms - -
info HTTP GET /datepicker/css/bootstrap-datepicker3.css 304 0.885 ms - -
info HTTP GET /css/footer.css 304 1.184 ms - -
info HTTP GET /css/mailtrain.css 304 0.193 ms - -
info HTTP GET /javascript/jquery-2.2.1.min.js 304 0.566 ms - -
info HTTP GET /bootstrap/js/bootstrap.min.js 304 0.966 ms - -
info HTTP GET /datepicker/js/bootstrap-datepicker.min.js 304 0.771 ms - -
info HTTP GET /datatables/datatables.min.js 304 1.060 ms - -
info HTTP GET /moment/moment.min.js 304 1.345 ms - -
info HTTP GET /javascript/tables.js 304 1.658 ms - -
info HTTP GET /javascript/fetch.js 304 0.194 ms - -
info HTTP POST /lists/ajax/1 200 9.423 ms - 59
info HTTP GET /lists/subscription/1/import 200 9.804 ms - -
info HTTP GET /bootstrap/themes/united.min.css 304 0.233 ms - -
info HTTP GET /datepicker/css/bootstrap-datepicker3.css 304 0.420 ms - -
info HTTP GET /datatables/datatables.min.css 304 0.723 ms - -
info HTTP GET /css/footer.css 304 0.266 ms - -
info HTTP GET /css/mailtrain.css 304 0.210 ms - -
info HTTP GET /javascript/jquery-2.2.1.min.js 304 0.254 ms - -
info HTTP GET /bootstrap/js/bootstrap.min.js 304 0.958 ms - -
info HTTP GET /datepicker/js/bootstrap-datepicker.min.js 304 1.257 ms - -
info HTTP GET /datatables/datatables.min.js 304 1.551 ms - -
info HTTP GET /moment/moment.min.js 304 1.829 ms - -
info HTTP GET /javascript/tables.js 304 2.147 ms - -
info HTTP GET /javascript/fetch.js 304 0.217 ms - -
verb tmpdir /tmp
verb Upload Storing upload to </tmp/mailtrain>
info HTTP POST /lists/subscription/import 302 1258.363 ms - 104
info HTTP GET /lists/subscription/1/import/2 200 19.053 ms - -
info HTTP GET /bootstrap/themes/united.min.css 304 0.407 ms - -
info HTTP GET /datatables/datatables.min.css 304 0.274 ms - -
info HTTP GET /datepicker/css/bootstrap-datepicker3.css 304 0.407 ms - -
info HTTP GET /css/footer.css 304 0.313 ms - -
info HTTP GET /css/mailtrain.css 304 0.301 ms - -
info HTTP GET /javascript/jquery-2.2.1.min.js 304 0.475 ms - -
info HTTP GET /bootstrap/js/bootstrap.min.js 304 1.333 ms - -
info HTTP GET /datepicker/js/bootstrap-datepicker.min.js 304 1.720 ms - -
info HTTP GET /datatables/datatables.min.js 304 1.954 ms - -
info HTTP GET /moment/moment.min.js 304 2.248 ms - -
info HTTP GET /javascript/tables.js 304 2.566 ms - -
info HTTP GET /javascript/fetch.js 304 1.021 ms - -
/usr/home/mailtrain/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'forEach' of undefined
    at fields.list (/usr/home/mailtrain/routes/lists.js:674:37)
    at Query.connection.query [as _callback] (/usr/home/mailtrain/lib/models/fields.js:89:20)
    at Query.Sequence.end (/usr/home/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/usr/home/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/usr/home/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/usr/home/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/usr/home/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/home/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/home/mailtrain/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mailtrain@1.23.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mailtrain@1.23.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-27T16_56_34_262Z-debug.log

Any help appreciated..

**Comment by jonathangilpin** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.4.2
3 info using node@v8.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mailtrain@1.23.2~prestart: mailtrain@1.23.2
6 info lifecycle mailtrain@1.23.2~start: mailtrain@1.23.2
7 verbose lifecycle mailtrain@1.23.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle mailtrain@1.23.2~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/home/mailtrain/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
9 verbose lifecycle mailtrain@1.23.2~start: CWD: /usr/home/mailtrain
10 silly lifecycle mailtrain@1.23.2~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle mailtrain@1.23.2~start: Returned: code: 1  signal: null
12 info lifecycle mailtrain@1.23.2~start: Failed to exec start script
13 verbose stack Error: mailtrain@1.23.2 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid mailtrain@1.23.2
15 verbose cwd /usr/home/mailtrain
16 verbose FreeBSD 11.1-RELEASE
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.4.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error mailtrain@1.23.2 start: `node index.js`
22 error Exit status 1
23 error Failed at the mailtrain@1.23.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by witzig** [comment]
Can you try with the latest commit?

**Comment by jonathangilpin** [comment]
Same problem.. maybe this will help:

File format is:

|Source|Category|Make|Model|Saluta|F Name|Surname|Job Title|Company|State|Country|E Mail|website|Year MNF|Aircraft Specific|Relationship|Last column|

<img width="729" alt="screenshot 2017-09-27 18 37 39" src="https://user-images.githubusercontent.com/7267219/30928287-1639b524-a3b3-11e7-89b5-afd35a1c2a5b.png">
<img width="1246" alt="screenshot 2017-09-27 18 37 33" src="https://user-images.githubusercontent.com/7267219/30928290-16960aa4-a3b3-11e7-8b52-467691b6d1f9.png">
<img width="1136" alt="screenshot 2017-09-27 18 37 21" src="https://user-images.githubusercontent.com/7267219/30928288-163ebba0-a3b3-11e7-9ee4-6267a57f866f.png">

**Comment by jonathangilpin** [comment]
Just to clarify that was after re-syncing. with git

**Comment by witzig** [comment]
This error is fixed now, correct?

```
TypeError: Cannot read property 'forEach' of undefined
at fields.list (/usr/home/mailtrain/routes/lists.js:674:37)
```

Got any new error logs?

**Comment by witzig** [comment]
Also, I assume you restarted Mailtrain after pulling the changes?!

**Comment by jonathangilpin** [comment]
Yes when it crashes it stops the application and I pulled the changes and started it again.. 

No, I still got the same error:

TypeError: Cannot read property 'forEach' of undefined
    at fields.list (/usr/home/mailtrain/routes/lists.js:674:37)

**Comment by witzig** [comment]
Hmm, I don't see the problem and can only try to reproduce. It'd be great if you could export your custom fields with:

`select * from custom_fields where list = YOUR_NUMERIC_LIST_ID;`

and also provide a csv file with a few (fake) subscribers. E-Mail me at git.witzig@icloud.com if you don't want to post it here.

**Comment by jonathangilpin** [comment]
<pre>
+----+------+-------------------+-------------------------+---------------+--------+-------+----------------+-----------------------------------+---------+---------------------+
| id | list | name              | key                     | default_value | type   | group | group_template | column                            | visible | created             |
+----+------+-------------------+-------------------------+---------------+--------+-------+----------------+-----------------------------------+---------+---------------------+
|  1 |    1 | Model             | MERGE_MODEL             | NULL          | number |  NULL | NULL           | custom_model_rj5ls8djb            |       1 | 2017-09-26 23:30:10 |
|  2 |    1 | Make              | MERGE_MAKE              | NULL          | text   |  NULL | NULL           | custom_make_byhupitib             |       1 | 2017-09-27 17:52:35 |
|  3 |    1 | Source            | MERGE_SOURCE            | NULL          | text   |  NULL | NULL           | custom_source_syqdviyoz           |       1 | 2017-09-27 17:52:50 |
|  4 |    1 | Website           | MERGE_WEBSITE           | NULL          | text   |  NULL | NULL           | custom_website_rjxovufsw          |       1 | 2017-09-27 17:52:59 |
|  5 |    1 | Company           | MERGE_COMPANY           | NULL          | text   |  NULL | NULL           | custom_company_rjpddukoz          |       1 | 2017-09-27 17:53:09 |
|  6 |    1 | Year MNF          | MERGE_YEAR_MNF          | NULL          | text   |  NULL | NULL           | custom_year_mnf_bymcwufib         |       1 | 2017-09-27 17:53:30 |
|  7 |    1 | RelationShip      | MERGE_RELATIONSHIP      | NULL          | text   |  NULL | NULL           | custom_relationship_byc5putoz     |       1 | 2017-09-27 17:53:41 |
|  8 |    1 | State             | MERGE_STATE             | NULL          | text   |  NULL | NULL           | custom_state_s11pwitiw            |       1 | 2017-09-27 17:54:15 |
|  9 |    1 | Aircraft Specific | MERGE_AIRCRAFT_SPECIFIC | NULL          | text   |  NULL | NULL           | custom_aircraft_specific_hyrw8fjw |       1 | 2017-09-27 17:54:33 |
+----+------+-------------------+-------------------------+---------------+--------+-------+----------------+-----------------------------------+---------+---------------------+
</pre>

Theres are the fields, however I think I've narrowed down the problem to an issue with the CSV file.. it had some lines in it which were basically like this:

-----------------------------------

I've removed those and it now works much more as expected and does not crash.. I went sent the sample to your email address...

**Comment by witzig** [comment]
Thanks @jonathangilpin. The culprit is indeed an invalid csv file whereby the first two lines look like this:

```
| Company, LLC    | CA   | United States          | mail@example.com     |  John   | Doe |
------------------------------------------------------------------------------------------
```

The first line should be the column headers, the second line the first subscriber:

```
Company|Sate|Country|Email|FirstName|LastName
Company, LLC|CA| United States|mail@example.com|John|Doe
```

If that's not the case then the mapping to custom fields be configured properly. Granted, this shouldn't crash Mailtrain when you start the import. I'll look into this.
