### ISSUE TITLE
postfixbounce error on sent email

### ISSUE THREAD

**Issue by osixia** [Mailtrain-org/mailtrain#343]
Hello, 
i have this error with POSTFIXBOUNCE when i send an email via postfix (not necessarey coming from mailtrain)

mailtrain error:
```
verb POSTFIXBOUNCE Checking message B75D029C3D42 for local requeue (status: sent)
/app/services/postfix-bounce-server.js:51
                        queued_as = queued_as[1];
                                             ^
 TypeError: Cannot read property '1' of null
    at checkNextLine (/app/services/postfix-bounce-server.js:51:46)
    at checkNextLine (/app/services/postfix-bounce-server.js:88:24)
    at checkNextLine (/app/services/postfix-bounce-server.js:88:24)
    at checkNextLine (/app/services/postfix-bounce-server.js:88:24)
    at checkNextLine (/app/services/postfix-bounce-server.js:88:24)
    at checkNextLine (/app/services/postfix-bounce-server.js:88:24)
    at checkNextLine (/app/services/postfix-bounce-server.js:88:24)
    at checkNextLine (/app/services/postfix-bounce-server.js:88:24)
    at checkNextLine (/app/services/postfix-bounce-server.js:88:24)
    at readNextChunk (/app/services/postfix-bounce-server.js:92:9)
```

mail.log
```
Oct 12 13:03:34 hostname postfix/smtpd[225]: connect from unknown[xx.xx.xx.xx]
Oct 12 13:03:34 hostname postfix/smtpd[225]: Anonymous TLS connection established from unknown[xx.xx.xx.xx]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Oct 12 13:03:34 hostname postfix/smtpd[225]: B75D029C3D42: client=unknown[xx.xx.xx.xx]
Oct 12 13:03:34 hostname postfix/cleanup[229]: B75D029C3D42: message-id=<a0e7f02e165ef673091912dc4db9cec8@xxx.fr>
Oct 12 13:03:34 hostname postfix/qmgr[217]: B75D029C3D42: from=<xxx.xxx@xxx.fr>, size=1848, nrcpt=1 (queue active)
Oct 12 13:03:34 hostname postfix/smtpd[225]: disconnect from unknown[xx.xx.xx.xx] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Oct 12 13:03:34 hostname postfix/smtp[230]: Untrusted TLS connection established to gmail-smtp-in.l.google.com[74.125.140.27]:25: TLSv1.2 with cipher ECDHE-RSA-CHACHA20-POLY1305 (256/256 bits)
Oct 12 13:03:35 hostname postfix/smtp[230]: B75D029C3D42: to=<xxx.xxx@xxx.com>, relay=gmail-smtp-in.l.google.com[74.125.140.27]:25, delay=0.52, delays=0.04/0/0.26/0.21, dsn=2.0.0, status=sent (250 2.0.0 OK 1507813415 l41si8913084wre.351 - gsmtp)
Oct 12 13:03:35 hostname postfix/qmgr[217]: B75D029C3D42: removed
```

**Comment by andris9** [comment]
Are you using the latest version of Mailtrain (eg. the version in the master branch)?

**Comment by osixia** [comment]
Oh sorry,
I'm using an outdated master branch, i will test with the latest and let you know.

Thanks

**Comment by osixia** [comment]
it's ok on the last master :)
sorry for the noise
