### ISSUE TITLE
Redis Issue

### ISSUE THREAD

**Issue by radleta** [Mailtrain-org/mailtrain#37]
I've run into an issue when I turn on redis for session management. I turn it on and I get the below error in the logs with the site crashing hard. I'm guessing the redis connection is failing.

Does the redis connection get verified on start up?

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/data/mailtrain/node_modules/express/lib/response.js:718:10)
    at ServerResponse.contentType (/data/mailtrain/node_modules/express/lib/response.js:551:15)
    at ServerResponse.send (/data/mailtrain/node_modules/express/lib/response.js:138:14)
    at done (/data/mailtrain/node_modules/express/lib/response.js:957:10)
    at /data/mailtrain/node_modules/hbs/lib/hbs.js:93:9
    at done (/data/mailtrain/node_modules/hbs/lib/async.js:74:20)
    at /data/mailtrain/node_modules/hbs/lib/hbs.js:88:18
    at render_file (/data/mailtrain/node_modules/hbs/lib/hbs.js:49:14)
    at render_with_layout (/data/mailtrain/node_modules/hbs/lib/hbs.js:80:5)
```

**Comment by andris9** [comment]
Can you describe how you ended up with this error as I'm not able to replicate this. Does this happen all the time, eg. no request succeeds, or does it happen on specific requests or does it happen randomly?

**Comment by radleta** [comment]
It happened when trying to log in or access user information. I'll spend some time diagnosing and see if I can give you more details.

**Comment by witzig** [comment]
Closing this old issue. Please re-open if the problem persists.

**Comment by ksbek** [comment]
I'm getting same error when I enabled redis.

info HTTP GET / 304 45.320 ms - -
Error: /home/ec2-user/gpl-denali-mailtrain/views/error.hbs: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (/home/ec2-user/gpl-denali-mailtrain/node_modules/express/lib/response.js:767:10)
    at ServerResponse.contentType (/home/ec2-user/gpl-denali-mailtrain/node_modules/express/lib/response.js:595:15)
    at ServerResponse.send (/home/ec2-user/gpl-denali-mailtrain/node_modules/express/lib/response.js:145:14)
    at done (/home/ec2-user/gpl-denali-mailtrain/node_modules/express/lib/response.js:1004:10)
    at /home/ec2-user/gpl-denali-mailtrain/node_modules/hbs/lib/hbs.js:93:9
    at Object.done (/home/ec2-user/gpl-denali-mailtrain/node_modules/hbs/lib/async.js:74:20)
    at /home/ec2-user/gpl-denali-mailtrain/node_modules/hbs/lib/hbs.js:88:18
    at /home/ec2-user/gpl-denali-mailtrain/node_modules/hbs/lib/hbs.js:69:11

I can't replicate this error on my local machine. 
I'm getting this error when I tried to deploy this on cloud server. It's really weird.
The node version is 8.9.4 and npm version is 5.6.0
