### ISSUE TITLE
Redis session issue

### ISSUE THREAD

**Issue by ksbek** [Mailtrain-org/mailtrain#371]
I'm getting following error when I enabled redis.

info HTTP GET / 304 45.320 ms - -
Error: /home/ec2-user/gpl-denali-mailtrain/views/error.hbs: Can't set headers after they are sent.
at validateHeader (_http_outgoing.js:494:11)
at ServerResponse.setHeader (_http_outgoing.js:501:3)
at ServerResponse.header (/home/ec2-user/gpl-denali-mailtrain/node_modules/express/lib/response.js:767:10)
at ServerResponse.contentType (/home/ec2-user/gpl-denali-mailtrain/node_modules/express/lib/response.js:595:15)
at ServerResponse.send (/home/ec2-user/gpl-denali-mailtrain/node_modules/express/lib/response.js:145:14)
at done (/home/ec2-user/gpl-denali-mailtrain/node_modules/express/lib/response.js:1004:10)
at /home/ec2-user/gpl-denali-mailtrain/node_modules/hbs/lib/hbs.js:93:9
at Object.done (/home/ec2-user/gpl-denali-mailtrain/node_modules/hbs/lib/async.js:74:20)
at /home/ec2-user/gpl-denali-mailtrain/node_modules/hbs/lib/hbs.js:88:18
at /home/ec2-user/gpl-denali-mailtrain/node_modules/hbs/lib/hbs.js:69:11

I can't replicate this error on my local machine.
I'm getting this error when I tried to deploy this on cloud server. It's really weird.
The node version is 8.9.4 and npm version is 5.6.0

**Comment by ksbek** [comment]
I resolved this issue.
The redis version on the cloud machine was 2.4.
I updated redis to 4.0 and fix the warnings appeared after started redis-server.
So finally the error was gone.
Thanks.
