### ISSUE TITLE
Running Mailtrain via systemd 

### ISSUE THREAD

**Issue by rodti** [Mailtrain-org/mailtrain#388]
I had some problems with the posix module when installing Mailtrain but have finally got Mailtrain running under a Mailtrain user.  

Mailtrain is installed in /opt/mailtrain on a Debian 9.3 system, all node packages were installed in that folder as user mailtran, and, I can execute `NODE_ENV=production npm start ` as user Mailtrain and connect successfully from a browser.  My production.toml sets user and group to ‘mailtrain’.

I added a systemd startup script from the Mailtrain setup folder and have enabled it.  Unfortunately when I try and start it this way it fails.  

Error is:

`Feb 25 21:51:26 bakery systemd[1]: Started Mailtrain server.
Feb 25 21:51:28 bakery node[6549]: info Using local auth
Feb 25 21:51:28 bakery node[6549]: /opt/mailtrain/node_modules/posix/lib/posix/index.js:21
Feb 25 21:51:28 bakery node[6549]:                 throw error;
Feb 25 21:51:28 bakery node[6549]:                 ^
Feb 25 21:51:28 bakery node[6549]: Error: Module version mismatch. Expected 48, got 59.
Feb 25 21:51:28 bakery node[6549]:     at Error (native)
Feb 25 21:51:28 bakery node[6549]:     at Object.Module._extensions..node (module.js:604:18)
Feb 25 21:51:28 bakery node[6549]:     at Module.load (module.js:494:32)
Feb 25 21:51:28 bakery node[6549]:     at tryModuleLoad (module.js:453:12)
Feb 25 21:51:28 bakery node[6549]:     at Function.Module._load (module.js:445:3)
Feb 25 21:51:28 bakery node[6549]:     at Module.require (module.js:504:17)
Feb 25 21:51:28 bakery node[6549]:     at require (internal/module.js:20:19)
Feb 25 21:51:28 bakery node[6549]:     at load_extension (/opt/mailtrain/node_modules/posix/lib/posix/index.js:16:20)
Feb 25 21:51:28 bakery node[6549]:     at Object.<anonymous> (/opt/mailtrain/node_modules/posix/lib/posix/index.js:28:13)
Feb 25 21:51:28 bakery node[6549]:     at Module._compile (module.js:577:32)
Feb 25 21:51:28 bakery systemd[1]: mailtrain.service: Main process exited, code=exited, status=1/FAILURE
Feb 25 21:51:28 bakery systemd[1]: mailtrain.service: Unit entered failed state.
Feb 25 21:51:28 bakery systemd[1]: mailtrain.service: Failed with result 'exit-code'.`

This is a similar posix module error to the issues I had when originally installing.

I’m not particularly good with node/npm, but wondering if installing the node modules as Mailtrain user has caused an issue when running the systemd script?

Any help appreciated! Frustrating that I’m so close yet so far away!

**Comment by rodti** [comment]
I’ve also tried changing the mailtrain.service script to use user and group ‘mailtrain’

**Comment by rodti** [comment]
Sorted. I changed `/usr/bin/node index.js` in the startup script to `/usr/bin/npm start` and added back in the user and group settings.
