### ISSUE TITLE
ERR! Link Error: ER_DATA_TOO_LONG: Data too long for column 'url' at row 1

### ISSUE THREAD

**Issue by killua-eu** [Mailtrain-org/mailtrain#463]
Hi all, I noticed some mysql errors due to Facebook links not fitting in the `links.url` field, which is a varchar(255). 

```
| links | CREATE TABLE `links` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `cid` varchar(255) CHARACTER SET ascii NOT NULL DEFAULT '',
  `campaign` int(11) unsigned NOT NULL,
  `url` varchar(255) CHARACTER SET ascii NOT NULL DEFAULT '',
  `clicks` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `cid` (`cid`),
  UNIQUE KEY `campaign_2` (`campaign`,`url`),
  KEY `campaign` (`campaign`),
  CONSTRAINT `links_ibfk_1` FOREIGN KEY (`campaign`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4424 DEFAULT CHARSET=utf8mb4 |
```

The obvious quickfix would be changing varchar to i.e. text, but this requires also index changes, because indexes on text fields have to be hard limited to a certain length. Playing with unique keys might break things, so I'm keeping this now only as an initial bug report.

```
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link Error: ER_DATA_TOO_LONG: Data too long for column 'url' at row 1
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Query.Sequence._packetToError (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Query.ErrorPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:91:28)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.emit (events.js:182:13)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.EventEmitter.emit (domain.js:442:20)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at addChunk (_stream_readable.js:283:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     --------------------
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._enqueue (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at PoolConnection.query (/opt/mailtrain/node_modules/mysql/lib/Connection.js:200:25)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at db.getConnection (/opt/mailtrain/lib/models/links.js:242:20)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.onOperationComplete (/opt/mailtrain/node_modules/mysql/lib/Pool.js:110:5)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping._callback (/opt/mailtrain/node_modules/mysql/lib/Connection.js:468:16)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.OkPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link  { Error: ER_DATA_TOO_LONG: Data too long for column 'url' at row 1
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Query.Sequence._packetToError (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Query.ErrorPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:91:28)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.emit (events.js:182:13)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.EventEmitter.emit (domain.js:442:20)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at addChunk (_stream_readable.js:283:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     --------------------
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._enqueue (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at PoolConnection.query (/opt/mailtrain/node_modules/mysql/lib/Connection.js:200:25)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at db.getConnection (/opt/mailtrain/lib/models/links.js:242:20)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.onOperationComplete (/opt/mailtrain/node_modules/mysql/lib/Pool.js:110:5)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping._callback (/opt/mailtrain/node_modules/mysql/lib/Connection.js:468:16)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.OkPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   stack:
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link    'Error: ER_DATA_TOO_LONG: Data too long for column \'url\' at row 1\n    at Query.Sequence._packetToError (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Query.ErrorPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)\n    at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at addChunk (_stream_readable.js:283:12)\n    --------------------\n    at Protocol._enqueue (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at PoolConnection.query (/opt/mailtrain/node_modules/mysql/lib/Connection.js:200:25)\n    at db.getConnection (/opt/mailtrain/lib/models/links.js:242:20)\n    at Ping.onOperationComplete (/opt/mailtrain/node_modules/mysql/lib/Pool.js:110:5)\n    at Ping.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)\n    at Ping._callback (/opt/mailtrain/node_modules/mysql/lib/Connection.js:468:16)\n    at Ping.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)\n    at Ping.Sequence.OkPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)\n    at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)\n    at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   code: 'ER_DATA_TOO_LONG',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   errno: 1406,
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   sqlMessage: 'Data too long for column \'url\' at row 1',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   sqlState: '22001',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   index: 0,
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   sql:
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link    'INSERT INTO links (`cid`, `campaign`, `url`) VALUES (\'3ROEldEy3d\',1,\'https://www.facebook.com/events/xxxxxxxxxxxxxxxx/?acontext=%7B%22source%22%3A3%2C%22source_newsfeed_story_type%22%3A%22regular%22%2C%22action_history%22%3A%22%5B%7B%5C%22surface%5C%22%3A%5C%22newsfeed%5C%22%2C%5C%22mechanism%5C%22%3A%5C%22feed_story%5C%22%2C%5C%22extra_data%5C%22%3A%5B%5D%7D%5D%22%2C%22has_source%22%3Atrue%7D&source=3&source_newsfeed_story_type=regular&action_history=%5B%7B%22surface%22%3A%22newsfeed%22%2C%22mechanism%22%3A%22feed_story%22%2C%22extra_data%22%3A%5B%5D%7D%5D&has_source=1&fref=mentions\')' }
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link Error: ER_DATA_TOO_LONG: Data too long for column 'url' at row 1
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Query.Sequence._packetToError (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Query.ErrorPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:91:28)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.emit (events.js:182:13)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.EventEmitter.emit (domain.js:442:20)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at addChunk (_stream_readable.js:283:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     --------------------
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._enqueue (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at PoolConnection.query (/opt/mailtrain/node_modules/mysql/lib/Connection.js:200:25)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at db.getConnection (/opt/mailtrain/lib/models/links.js:242:20)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.onOperationComplete (/opt/mailtrain/node_modules/mysql/lib/Pool.js:110:5)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping._callback (/opt/mailtrain/node_modules/mysql/lib/Connection.js:468:16)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.OkPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping._callback (/opt/mailtrain/node_modules/mysql/lib/Connection.js:468:16)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.OkPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   stack:
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link    'Error: ER_DATA_TOO_LONG: Data too long for column \'url\' at row 1\n    at Query.Sequence._packetToError (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Query.ErrorPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)\n    at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at addChunk (_stream_readable.js:283:12)\n    --------------------\n    at Protocol._enqueue (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at PoolConnection.query (/opt/mailtrain/node_modules/mysql/lib/Connection.js:200:25)\n    at db.getConnection (/opt/mailtrain/lib/models/links.js:242:20)\n    at Ping.onOperationComplete (/opt/mailtrain/node_modules/mysql/lib/Pool.js:110:5)\n    at Ping.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)\n    at Ping._callback (/opt/mailtrain/node_modules/mysql/lib/Connection.js:468:16)\n    at Ping.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)\n    at Ping.Sequence.OkPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)\n    at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)\n    at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   code: 'ER_DATA_TOO_LONG',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   errno: 1406,
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   sqlMessage: 'Data too long for column \'url\' at row 1',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   sqlState: '22001',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   index: 0,
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   sql:
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link    'INSERT INTO links (`cid`, `campaign`, `url`) VALUES (\'jhcKkGFp1s\',1,\'https://www.facebook.com/events/xxxxxxxxxxxxxx/?acontext=%7B%22source%22%3A3%2C%22source_newsfeed_story_type%22%3A%22regular%22%2C%22action_history%22%3A%22%5B%7B%5C%22surface%5C%22%3A%5C%22newsfeed%5C%22%2C%5C%22mechanism%5C%22%3A%5C%22feed_story%5C%22%2C%5C%22extra_data%5C%22%3A%5B%5D%7D%5D%22%2C%22has_source%22%3Atrue%7D&source=3&source_newsfeed_story_type=regular&action_history=%5B%7B%22surface%22%3A%22newsfeed%22%2C%22mechanism%22%3A%22feed_story%22%2C%22extra_data%22%3A%5B%5D%7D%5D&has_source=1&fref=mentions\')' }
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link Error: ER_DATA_TOO_LONG: Data too long for column 'url' at row 1
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Query.Sequence._packetToError (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Query.ErrorPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:91:28)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.emit (events.js:182:13)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Socket.EventEmitter.emit (domain.js:442:20)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at addChunk (_stream_readable.js:283:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     --------------------
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._enqueue (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at PoolConnection.query (/opt/mailtrain/node_modules/mysql/lib/Connection.js:200:25)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at db.getConnection (/opt/mailtrain/lib/models/links.js:242:20)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.onOperationComplete (/opt/mailtrain/node_modules/mysql/lib/Pool.js:110:5)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping._callback (/opt/mailtrain/node_modules/mysql/lib/Connection.js:468:16)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Ping.Sequence.OkPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link     at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   stack:
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link    'Error: ER_DATA_TOO_LONG: Data too long for column \'url\' at row 1\n    at Query.Sequence._packetToError (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Query.ErrorPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)\n    at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)\n    at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at addChunk (_stream_readable.js:283:12)\n    --------------------\n    at Protocol._enqueue (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at PoolConnection.query (/opt/mailtrain/node_modules/mysql/lib/Connection.js:200:25)\n    at db.getConnection (/opt/mailtrain/lib/models/links.js:242:20)\n    at Ping.onOperationComplete (/opt/mailtrain/node_modules/mysql/lib/Pool.js:110:5)\n    at Ping.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:502:10)\n    at Ping._callback (/opt/mailtrain/node_modules/mysql/lib/Connection.js:468:16)\n    at Ping.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)\n    at Ping.Sequence.OkPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)\n    at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:278:23)\n    at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:76:12)',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   code: 'ER_DATA_TOO_LONG',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   errno: 1406,
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   sqlMessage: 'Data too long for column \'url\' at row 1',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   sqlState: '22001',
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   index: 0,
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link   sql:
Aug 30 00:04:09 az01-mailtrain node[142]: ERR! Link    'INSERT INTO links (`cid`, `campaign`, `url`) VALUES (\'H-_XGylOjy\',1,\'https://www.facebook.com/events/xxxxxxxxxxxxxxxx/?acontext=%7B%22source%22%3A3%2C%22source_newsfeed_story_type%22%3A%22regular%22%2C%22action_history%22%3A%22%5B%7B%5C%22surface%5C%22%3A%5C%22newsfeed%5C%22%2C%5C%22mechanism%5C%22%3A%5C%22feed_story%5C%22%2C%5C%22extra_data%5C%22%3A%5B%5D%7D%5D%22%2C%22has_source%22%3Atrue%7D&source=3&source_newsfeed_story_type=regular&action_history=%5B%7B%22surface%22%3A%22newsfeed%22%2C%22mechanism%22%3A%22feed_story%22%2C%22extra_data%22%3A%5B%5D%7D%5D&has_source=1&fref=mentions\')' }
```

**Comment by bures** [comment]
Good catch. I'll see whether I can use text type for links in Mailtrain 2.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
