### ISSUE TITLE
V2 - Installation on Ubuntu 18.04 fails

### ISSUE THREAD

**Issue by tmikaeld** [Mailtrain-org/mailtrain#558]
Node build output:
```
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.3' ]
gyp verb remove using node-gyp dir: /opt/mailtrain/client/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.3
gyp verb remove removing development files for version: 10.15.3
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/mailtrain/client/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/usr/bin/node" "/opt/mailtrain/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/mailtrain/client/node_modules/node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Logfile:

```
32805 silly saveTree   │   │   └── is-extglob@2.1.1
32805 silly saveTree   │   └── is-glob@4.0.0
32805 silly saveTree   └── webpack-sources@1.3.0
32806 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
32807 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x$
32808 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
32808 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
32808 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
32808 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
32809 verbose stack Error: node-sass@4.11.0 postinstall: `node scripts/build.js`
32809 verbose stack Exit status 1
32809 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
32809 verbose stack     at EventEmitter.emit (events.js:189:13)
32809 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
32809 verbose stack     at ChildProcess.emit (events.js:189:13)
32809 verbose stack     at maybeClose (internal/child_process.js:970:16)
32809 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
32810 verbose pkgid node-sass@4.11.0
32811 verbose cwd /opt/mailtrain/client
32812 verbose Linux 4.15.0-45-generic
32813 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
32814 verbose node v10.15.3
32815 verbose npm  v6.4.1
32816 error code ELIFECYCLE
32817 error errno 1
32818 error node-sass@4.11.0 postinstall: `node scripts/build.js`
32818 error Exit status 1
32819 error Failed at the node-sass@4.11.0 postinstall script.
32819 error This is probably not a problem with npm. There is likely additional logging output above.
32820 verbose exit [ 1, true ]

**Comment by bures** [comment]
Did you try the `sudo su -`?

**Comment by tmikaeld** [comment]
I'm running the install script as root user?

**Comment by bures** [comment]
You mean you did ssh root@.... or you logged in as root, right?

**Comment by tmikaeld** [comment]
Logged in as root, yes.

Everything else installs fine and cert is created, but the node installation fails.

**Comment by tmikaeld** [comment]
I did a complete re-install of the server, the previous issue is gone.

However, now it stops at:

```
Reinstalling modules in mvis/ivis-core/client
/opt/mailtrain/setup/functions: line 222: cd: mvis/ivis-core/client: No such file or directory

**Comment by bures** [comment]
Just pull the latest version. I fixed the issue with the mvis/ivis-core/client

**Comment by bures** [comment]
I mean I fixed it right now.

**Comment by tmikaeld** [comment]
Thanks, I'll try it again when Let's encrypt haven't blocked my IP for issuing too many times.

**Comment by tmikaeld** [comment]
Works now, thanks for the help!
