### ISSUE TITLE
Import of users.csv results in 502 error

### ISSUE THREAD

**Issue by ansgarsmith** [Mailtrain-org/mailtrain#585]
I just finalized the installation of Mailtrain v2. And so far everything seems to be working in good order. We can send campaigns, and the API seems to be working. Except for one thing: import of users is resulting in a 502 error.

![image](https://user-images.githubusercontent.com/46681263/56427176-30e17880-62bb-11e9-8f1f-7a4c96f6a9c9.png)

How do I trouble shoot this? I attached a testfile that I used for importing.

When restarting mailtrain, I get the following output:
info Using local auth
info sql Database check completed
info Executor Executor process started.
info Express WWW server [trusted] listening on port 10000
info Express WWW server [sandbox] listening on port 10003
info Express WWW server [public] listening on port 10004
info Importer Importer process started
(node:3237) UnhandledPromiseRejectionWarning: Error: ER_TABLE_EXISTS_ERROR: Tabl                                  e 'import_file__2' already exists
    at Query.Sequence._packetToError (/var/www/vhosts/<domain>/httpdocs/ma                                  iltrain-beta/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta                                  /server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/var/www/vhosts/<domain>/httpdocs/mailtrain-                                  beta/server/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta/serv                                  er/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta/se                                  rver/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/vhosts/<domain>/httpdocs/mailtrain-bet                                  a/server/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/var/www/vhosts/<domain>/httpdocs/mailtrain-bet                                  a/server/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta                                  /server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta/                                  server/node_modules/mysql/lib/Connection.js:200:25)
    at /var/www/vhosts/<domain>/httpdocs/mailtrain-beta/server/node_module                                  s/knex/lib/dialects/mysql/index.js:144:18
    at Promise._execute (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta/                                  server/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/var/www/vhosts/<domain>/httpdocs/mai                                  ltrain-beta/server/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta/serve                                  r/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/var/www/vhosts/<domain>/httpdocs/mailtrain-be                                  ta/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
    at Client_MySQL.query (/var/www/vhosts/<domain>/httpdocs/mailtrain-bet                                  a/server/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/var/www/vhosts/<domain>/httpdocs/mailtrain-bet                                  a/server/node_modules/knex/lib/runner.js:138:36)
    at Runner.tryCatcher (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta                                  /server/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta/serv                                  er/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.queryArray (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta                                  /server/node_modules/knex/lib/runner.js:205:40)
    at /var/www/vhosts/<domain>/httpdocs/mailtrain-beta/server/node_module                                  s/knex/lib/runner.js:44:23
    at tryCatcher (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta/server                                  /node_modules/bluebird/js/release/util.js:16:23)
    at /var/www/vhosts/<domain>/httpdocs/mailtrain-beta/server/node_module                                  s/bluebird/js/release/using.js:185:26
    at tryCatcher (/var/www/vhosts/<domain>/httpdocs/mailtrain-beta/server                                  /node_modules/bluebird/js/release/util.js:16:23)
(node:3237) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                   error originated either by throwing inside of an async function without a catch                                   block, or by rejecting a promise which was not handled with .catch(). (rejection                                   id: 1)
(node:3237) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre                                  cated. In the future, promise rejections that are not handled will terminate the                                   Node.js process with a non-zero exit code.
info Feed Feedcheck process started
info Senders Worker process 1 started
info Senders Worker process 0 started
info Senders Master sender process started
info Triggers Starting trigger check service
info GDPR Starting GDPR cleanup service
info ReportProcessor Trying to start worker because runningWorkersCount=0 maxWorkersCount=1
info ReportProcessor No more reports to start a worker for
info Service All services started
ERR! Importer Importer process exited with code null signal SIGKILL

Within the MYSQL database I see nicely that all users have been added in an table: import_file__x ready to be imported.

When I restart mailtrain I can see that the file is ready to be imported, but something seems to be wrong with the date. See image:

![image](https://user-images.githubusercontent.com/46681263/56428024-40ae8c00-62be-11e9-9614-507f300a368b.png)

I added the csv file (as .txt) for reference
[test.txt](https://github.com/Mailtrain-org/mailtrain/files/3098303/test.txt)

Any thoughts?

**Comment by ansgarsmith** [comment]
@all, forget about it. The real import file was 5MB, with a gazillion empty rows and Mailtrain simply chocked on that. I removed all failed imports an re-tried. Now it's all goed.
