### ISSUE TITLE
Problem pausing a campaign v2

### ISSUE THREAD

**Issue by ansgarsmith** [Mailtrain-org/mailtrain#593]
We have a campaigng being sent out to a list of 9000. It's a scheduled campaign. We want to pause the sending proces. When clicking on the "Stop" button it does not work. And I notice Javascript errors;  /rest/campaign-stop/6  500 (internal server error)

![image](https://user-images.githubusercontent.com/46681263/57148370-c0158280-6dc9-11e9-9ea1-ffa0a3c248c0.png)

Anyone experiencing the same?

**Comment by jameshobden** [comment]
Please can you post your logs?

**Comment by ansgarsmith** [comment]
which logs exactly? something like:

`journalctl | grep mailtrain`

**Comment by bures** [comment]
journalctl -u mailtrain

**Comment by ansgarsmith** [comment]
thanks. old logs are destroyed qas we reinstalled everything on a new server, so I need to run a slow-drip test this evening to reproduce the issue and get some fresh logs. Will post it a.s.a.p.

**Comment by ansgarsmith** [comment]
Got it:

```
mei 10 13:36:05 h2834667.stratoserver.net node[2018]: verb Senders Message sent and status updated for 6:xxxxxx@gmail.com
mei 10 13:36:05 h2834667.stratoserver.net node[2018]: verb Mail Throttling next message in 20.988470588235295 sec.
mei 10 13:36:07 h2834667.stratoserver.net node[2018]: info HTTP GET /rest/campaigns-stats/18 200 9.013 ms - 768
mei 10 13:36:08 h2834667.stratoserver.net node[2018]: info HTTP GET /rest/send-configurations-public/1 304 8.686 ms - -
mei 10 13:36:08 h2834667.stratoserver.net node[2018]: info HTTP GET /links/tNVh4ZvRW/k-7JsuCsC/f2lo9g6ssD 200 0.508 ms - 42
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: verb HTTP Error: Cannot stop campaign until it is in SCHEDULED state
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: verb HTTP     at knex.transaction (/var/www/vhosts/<removed>/httpdocs/mailtrain-beta/server/models/campaigns.js:856:19)
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: verb HTTP  { Error: Cannot stop campaign until it is in SCHEDULED state
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: verb HTTP     at knex.transaction (/var/www/vhosts/<removed>/httpdocs/mailtrain-beta/server/models/campaigns.js:856:19)
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: verb HTTP   stack:
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: verb HTTP    'Error: Cannot stop campaign until it is in SCHEDULED state\n    at knex.transaction (/var/www/vhosts/<removed>/httpdocs/mailtrain-beta/server/models/campaigns.js:856:19)',
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: verb HTTP   type: 'InvalidStateError',
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: verb HTTP   data: undefined }
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: info HTTP POST /rest/campaign-stop/18 500 11.018 ms - 103
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: info HTTP GET /rest/campaigns-stats/18 200 10.066 ms - 768
mei 10 13:36:12 h2834667.stratoserver.net node[2018]: info HTTP GET /rest/send-configurations-public/1 304 9.756 ms - -

```

**Comment by ansgarsmith** [comment]
here is the log:

```
mei 10 13:36:05 <removed>et node[2018]: verb Senders Message sent and status updated for 6:xxxxxx@gmail.com
mei 10 13:36:05 <removed>et node[2018]: verb Mail Throttling next message in 20.988470588235295 sec.
mei 10 13:36:07 <removed>et node[2018]: info HTTP GET /rest/campaigns-stats/18 200 9.013 ms - 768
mei 10 13:36:08 <removed>et node[2018]: info HTTP GET /rest/send-configurations-public/1 304 8.686 ms - -
mei 10 13:36:08 <removed>et node[2018]: info HTTP GET /links/tNVh4ZvRW/k-7JsuCsC/f2lo9g6ssD 200 0.508 ms - 42
mei 10 13:36:12 <removed>et node[2018]: verb HTTP Error: Cannot stop campaign until it is in SCHEDULED state
mei 10 13:36:12 <removed>et node[2018]: verb HTTP     at knex.transaction (/var/www/vhosts/<removed>/httpdocs/mailtrain-beta/server/models/campaigns.js:856:19)
mei 10 13:36:12 <removed>et node[2018]: verb HTTP  { Error: Cannot stop campaign until it is in SCHEDULED state
mei 10 13:36:12 <removed>et node[2018]: verb HTTP     at knex.transaction (/var/www/vhosts/<removed>/httpdocs/mailtrain-beta/server/models/campaigns.js:856:19)
mei 10 13:36:12 <removed>et node[2018]: verb HTTP   stack:
mei 10 13:36:12 <removed>et node[2018]: verb HTTP    'Error: Cannot stop campaign until it is in SCHEDULED state\n    at knex.transaction (/var/www/vhosts/<removed>/httpdocs/mailtrain-beta/server/models/campaigns.js:856:19)',
mei 10 13:36:12 <removed>et node[2018]: verb HTTP   type: 'InvalidStateError',
mei 10 13:36:12 <removed>et node[2018]: verb HTTP   data: undefined }
mei 10 13:36:12 <removed>et node[2018]: info HTTP POST /rest/campaign-stop/18 500 11.018 ms - 103
mei 10 13:36:12 <removed>et node[2018]: info HTTP GET /rest/campaigns-stats/18 200 10.066 ms - 768
mei 10 13:36:12 <removed>et node[2018]: info HTTP GET /rest/send-configurations-public/1 304 9.756 ms - -


```

**Comment by bures** [comment]
I found the problem and fixed it in my personal development branch. Once I test the functionality and make sure there are no glitches, I'll push it to `development`. You can try it out then.

**Comment by bures** [comment]
I did some bigger changes in starting/pausing/... the campaign. It should work now. If not, please reopen the issue.
