### ISSUE TITLE
Having trouble upgrading to v2

### ISSUE THREAD

**Issue by snarlynarwhal** [Mailtrain-org/mailtrain#596]
Upon running: `NODE_ENV=production npm start` I get migration errors:
```
snarlynarwhal@halfhumangames:~/mailtrain/server$ NODE_ENV=production npm start

> mailtrain@2.0.0 start /home/snarlynarwhal/mailtrain/server
> node index.js

info Using local auth
info sql Database check completed
verb Migration Base complete
verb Migration Namespaces complete
verb Migration Users complete
verb Migration Custom forms complete
verb Migration Custom fields complete
migration file "20170506102634_v1_to_v2.js" failed
migration failed with error: update `subscription__1` set `id` = 2, `cid` = 'Bk6b9QpRG', `email` = 'randomemail@me.com', `opt_in_ip` = NULL, `opt_in_country` = NULL, `tz` = 'us/eastern', `imported` = NULL, `status` = 1, `is_test` = 1, `status_change` = '2018-05-19 04:37:25.000', `latest_open` = NULL, `latest_click` = NULL, `created` = '2018-05-19 04:37:24.000', `first_name` = 'John', `last_name` = 'Doe', `source_email` = -4, `hash_email` = 'EST8u/ELM8i9fWCiqfezbWJfIX+UyzNa0Cdw21X14txIuppnYgkIJ5s8kGrwwF1XJmLFwn7Na50Fr9hvtstc1Q==', `source_first_name` = -4, `source_last_name` = -4 where `id` = 2 - Out of range value for column 'source_email' at row 1
Unhandled rejection Error: Out of range value for column 'source_email' at row 1
    at Packet.asError (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/packets/packet.js:684:17)
    at Query.execute (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/connection.js:80:31)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

snarlynarwhal@halfhumangames:~/mailtrain/server$ NODE_ENV=production npm start

> mailtrain@2.0.0 start /home/snarlynarwhal/mailtrain/server
> node index.js

info Using local auth
info sql Database check completed
migration file "20170506102634_v1_to_v2.js" failed
migration failed with error: ALTER TABLE `custom_forms` MODIFY `list` int unsigned not null - Unknown column 'list' in 'custom_forms'
Unhandled rejection Error: Unknown column 'list' in 'custom_forms'
    at Packet.asError (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/packets/packet.js:684:17)
    at Query.execute (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/connection.js:80:31)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I exported my lists and dropped the database hoping it would fix it, but this error instead:

```
snarlynarwhal@halfhumangames:~/mailtrain/server$ NODE_ENV=production npm start

> mailtrain@2.0.0 start /home/snarlynarwhal/mailtrain/server
> node index.js

info Using local auth
info sql SQL not set up, initializing
info sql Loading tables from mailtrain.sql
info sql Update 25 applied
info sql Update 26 applied
info sql Update 27 applied
info sql Update 28 applied
info sql Update 29 applied
info sql Update 30 applied
info sql Update 31 applied
info sql Update 32 applied
info sql Update 33 applied
info sql Database check completed
verb Migration Base complete
verb Migration Namespaces complete
verb Migration Users complete
verb Migration Custom forms complete
verb Migration Custom fields complete
verb Migration Segments complete
verb Migration Reports complete
migration file "20170506102634_v1_to_v2.js" failed
migration failed with error: insert into `settings` (`key`, `value`) values ('uaCode', DEFAULT), ('shoutout', DEFAULT), ('adminEmail', 'admin@example.com'), ('defaultHomepage', 'http://localhost:3000/'), ('pgpPassphrase', DEFAULT), ('pgpPrivateKey', DEFAULT) - Field 'value' doesn't have a default value
Unhandled rejection Error: Field 'value' doesn't have a default value
    at Packet.asError (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/packets/packet.js:684:17)
    at Query.execute (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/snarlynarwhal/mailtrain/server/node_modules/mysql2/lib/connection.js:80:31)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by snarlynarwhal** [comment]
I started a fresh install and it worked. Not sure what I messed up the first time.
