### ISSUE TITLE
V2: Reports broken for Docker distribution

### ISSUE THREAD

**Issue by brentkearney** [Mailtrain-org/mailtrain#613]
It appears that the reports feature in V2 assumes that the mysql server is at 127.0.0.1, but when running in a Docker container, names should be used to map to the proper container.

```
{ Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
    --------------------
    at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/app/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/app/server/node_modules/mysql/lib/Connection.js:119:18)
    at _bluebird.default (/app/server/node_modules/knex/lib/dialects/mysql/index.js:82:18)
    at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/app/server/node_modules/knex/lib/dialects/mysql/index.js:77:12)
    at create (/app/server/node_modules/knex/lib/client.js:282:21)
    at utils_1.tryPromise (/app/server/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/app/server/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/app/server/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/app/server/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/app/server/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/app/server/node_modules/tarn/lib/Pool.js:208:36)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true }
```

**Comment by bures** [comment]
Yep. Indeed. We had an error in the docker-entrypoint.sh . Can you try it now?

**Comment by javicaballero** [comment]
The password is also hardcoded. If I choose a password other than 'mailtrain' for the 'mailtrain' user in the database, the following error message occurs: ER_ACCESS_DENIED_ERROR: Access denied for user 'mailtrain'@'172.19.0.3' (using password: YES). Can you check please? Thanks!
