### ISSUE TITLE
Installation compatibility on node 10.16

### ISSUE THREAD

**Issue by orvn** [Mailtrain-org/mailtrain#623]
Tried installing on a centos 7 server `node 10.16.0` and `npm 6.9.0`. Is it not compatible with these versions?

Tail of log output (after running `npm install --production`):
```
make: Entering directory `/home/undone/public/mailtrain/node_modules/posix/build'
  CXX(target) Release/obj.target/posix/src/posix.o
cc1plus: error: unrecognized command line option "-std=gnu++1y"
make: *** [Release/obj.target/posix/src/posix.o] Error 1
make: Leaving directory `/home/undone/public/mailtrain/node_modules/posix/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 2.6.32-754.10.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/undone/public/mailtrain/node_modules/posix
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.2 (node_modules/posix):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 691 packages from 748 contributors and audited 15288 packages in 43.287s
found 54 vulnerabilities (26 low, 12 moderate, 15 high, 1 critical)
```

**Comment by bures** [comment]
Is this Mailtrain v1 or v2 beta?

**Comment by orvn** [comment]
I did a `git clone https://github.com/Mailtrain-org/mailtrain.git`, so just the master branch there I guess which is on 1.23.2 by the look of it

**Comment by bures** [comment]
Yes. That's version 1. I'll be happy to help you with version 2 beta. v1 should work, but it's not actively maintained any more.

**Comment by orvn** [comment]
Thanks. I just cloned master so I didn't see there was a v2. These setup instructions are for my exact tech stack anyway so should work better
