### ISSUE TITLE
Mailtrain won't send messages

### ISSUE THREAD

**Issue by schneiderbw** [Mailtrain-org/mailtrain#674]
When I start mailtrain as root with `NODE_ENV=production npm start` everything works perfectly, but when I start it with systemd (verified using the same mailtrain.service that came with mailtrain) and try to send campaign, I get this in `journalctl -r`

```Aug 14 14:22:07 tsi-mail21 node[25539]: ERR! Child Sender process 33209 exited with 1
Aug 14 14:22:07 tsi-mail21 node[25539]:     at require (internal/module.js:11:18)
Aug 14 14:22:07 tsi-mail21 node[25539]:     at Module.require (module.js:596:17)
Aug 14 14:22:07 tsi-mail21 node[25539]:     at Function.Module._load (module.js:497:3)
Aug 14 14:22:07 tsi-mail21 node[25539]:     at tryModuleLoad (module.js:505:12)
Aug 14 14:22:07 tsi-mail21 node[25539]:     at Module.load (module.js:565:32)
Aug 14 14:22:07 tsi-mail21 node[25539]:     at Object.Module._extensions..js (module.js:663:10)
Aug 14 14:22:07 tsi-mail21 node[25539]:     at Module._compile (module.js:652:30)
Aug 14 14:22:07 tsi-mail21 node[25539]:     at Object.<anonymous> (/opt/mailtrain/lib/db.js:10:24)
Aug 14 14:22:07 tsi-mail21 node[25539]:     at Object.createPool (/opt/mailtrain/node_modules/mysql/index.js:26:28)
Aug 14 14:22:07 tsi-mail21 node[25539]:     at new PoolConfig (/opt/mailtrain/node_modules/mysql/lib/PoolConfig.js:10:38)
Aug 14 14:22:07 tsi-mail21 node[25539]: TypeError: Cannot read property 'acquireTimeout' of undefined
Aug 14 14:22:07 tsi-mail21 node[25539]:                                      ^
Aug 14 14:22:07 tsi-mail21 node[25539]:   this.acquireTimeout     = (options.acquireTimeout === undefined)
Aug 14 14:22:07 tsi-mail21 node[25539]: /opt/mailtrain/node_modules/mysql/lib/PoolConfig.js:10
```

Also here's the config of my mailtrain.service:
```
[Unit]
Description=Mailtrain server
Requires=mysql.service
After=syslog.target network.target

[Service]
Environment="NODE_ENV=production"
WorkingDirectory=/opt/mailtrain
ExecStart=/usr/bin/node index.js
Type=simple
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
# Alias=mailtrain.service
```

Running on Ubuntu Linux 18.04.1 with all patches.

**Comment by forgeOneHQ** [comment]
Please install the latest of mailtrain v2.

If still struggling please open an issue.
