### ISSUE TITLE
Migrations Failed

### ISSUE THREAD

**Issue by tiredofit** [Mailtrain-org/mailtrain#689]
I maintain a Docker Image of Mailtrain 2 (Unreleased at this time, soon!) and have just rebuild the image based on a fresh pull from the `develop` branch. Upon restarting, Migrations failed. I read some of your previous issues with regards to a bad migration, and attempted to perform a fresh install. I can load the DB Schema just fine, but when I start node I see migration failures.

Attached is the output:
````bash
 info Using local auth 
 info sql Database check completed
 migration file "20190629000000_add_start_at_to_campaigns.js" failed
 migration failed with error: alter table `campaigns` add `start_at` timestamp null - ER_DUP_FIELDNAME: Duplicate column name 'start_at'
 ERR! Error: ER_DUP_FIELDNAME: Duplicate column name 'start_at'
 ERR!     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
 ERR!     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
 ERR!     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
 ERR!     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
 ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
 ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
 ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
 ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
 ERR!     at Socket.emit (events.js:198:13)
 ERR!     at Socket.EventEmitter.emit (domain.js:448:20)
 ERR!     at addChunk (_stream_readable.js:288:12)
 ERR!     at readableAddChunk (_stream_readable.js:269:11)
 ERR!     at Socket.Readable.push (_stream_readable.js:224:10)
 ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
 ERR!     --------------------
 ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
 ERR!     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
 ERR!     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
 ERR!     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:313:9)
 ERR!     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:483:18)
 ERR!     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:79:10)
 ERR!     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
 ERR!     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
 ERR!     at /app/server/node_modules/knex/lib/transaction.js:232:21
 ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
 ERR!     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
 ERR!     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
 ERR!     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
 ERR!     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
 ERR!     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
 ERR!     at Runner.queryArray (/app/server/node_modules/knex/lib/runner.js:207:40)
 ERR!     at /app/server/node_modules/knex/lib/runner.js:44:23
 ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
 ERR!     at /app/server/node_modules/bluebird/js/release/using.js:185:26
 ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
 ERR!     at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:512:31)
 ERR!     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:569:18)
 ERR!  { Error: ER_DUP_FIELDNAME: Duplicate column name 'start_at'
 ERR!     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
 ERR!     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
 ERR!     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
 ERR!     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
 ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
 ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
````

**Comment by bures** [comment]
Can you send me the DB schema that fails the migration. I need the schema and the contents of knex_* tables.

**Comment by bures** [comment]
Not sure what the problem is. I tried the DB backup (before the failed migrations) that you provided. The migration successfully completes. No errors.
