### ISSUE TITLE
V2: Error while sending email via API - invalid send configuration ID

### ISSUE THREAD

**Issue by pelkkala** [Mailtrain-org/mailtrain#699]
I try to send out transactional email using API but I get the following error:

**Error: Invalid send configuration ID**

I have triple checked that the send configuration ID really is the correct one.

My POST data looks like this:

> $data = array (
				'EMAIL' => $userEmail,
				'SEND_CONFIGURATION_ID' => "J2JFqkuUo",
				'SUBJECT' => 'Welcome!'
> 				);

Here is the error snippet from my syslog:

> Sep 10 17:35:10 server1 node[17899]: verb HTTP Error: Invalid send configuration ID
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at castToInteger (/opt/mailtrain/server/lib/helpers.js:39:15)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at router.postAsync (/opt/mailtrain/server/routes/api.js:305:31)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at ret.(anonymous function) (/opt/mailtrain/server/lib/router-async.js:12:52)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Layer.handle [as handle_request] (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:95:5)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at next (/opt/mailtrain/server/node_modules/express/lib/router/route.js:137:13)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Route.dispatch (/opt/mailtrain/server/node_modules/express/lib/router/route.js:112:3)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Layer.handle [as handle_request] (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:95:5)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at /opt/mailtrain/server/node_modules/express/lib/router/index.js:281:22
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at param (/opt/mailtrain/server/node_modules/express/lib/router/index.js:354:14)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at param (/opt/mailtrain/server/node_modules/express/lib/router/index.js:365:14)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Function.process_params (/opt/mailtrain/server/node_modules/express/lib/router/index.js:410:3)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at next (/opt/mailtrain/server/node_modules/express/lib/router/index.js:275:10)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Function.handle (/opt/mailtrain/server/node_modules/express/lib/router/index.js:174:3)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at router (/opt/mailtrain/server/node_modules/express/lib/router/index.js:47:12)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Layer.handle [as handle_request] (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:95:5)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at trim_prefix (/opt/mailtrain/server/node_modules/express/lib/router/index.js:317:13)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at /opt/mailtrain/server/node_modules/express/lib/router/index.js:284:7
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Function.process_params (/opt/mailtrain/server/node_modules/express/lib/router/index.js:335:12)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at next (/opt/mailtrain/server/node_modules/express/lib/router/index.js:275:10)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at app.use (/opt/mailtrain/server/app-builder.js:268:9)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Layer.handle [as handle_request] (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:95:5)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at trim_prefix (/opt/mailtrain/server/node_modules/express/lib/router/index.js:317:13)
Sep 10 17:35:10 server1 node[17899]: verb HTTP  { Error: Invalid send configuration ID
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at castToInteger (/opt/mailtrain/server/lib/helpers.js:39:15)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at router.postAsync (/opt/mailtrain/server/routes/api.js:305:31)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at ret.(anonymous function) (/opt/mailtrain/server/lib/router-async.js:12:52)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Layer.handle [as handle_request] (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:95:5)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at next (/opt/mailtrain/server/node_modules/express/lib/router/route.js:137:13)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Route.dispatch (/opt/mailtrain/server/node_modules/express/lib/router/route.js:112:3)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Layer.handle [as handle_request] (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:95:5)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at /opt/mailtrain/server/node_modules/express/lib/router/index.js:281:22
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at param (/opt/mailtrain/server/node_modules/express/lib/router/index.js:354:14)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at param (/opt/mailtrain/server/node_modules/express/lib/router/index.js:365:14)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Function.process_params (/opt/mailtrain/server/node_modules/express/lib/router/index.js:410:3)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at next (/opt/mailtrain/server/node_modules/express/lib/router/index.js:275:10)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Function.handle (/opt/mailtrain/server/node_modules/express/lib/router/index.js:174:3)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at router (/opt/mailtrain/server/node_modules/express/lib/router/index.js:47:12)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Layer.handle [as handle_request] (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:95:5)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at trim_prefix (/opt/mailtrain/server/node_modules/express/lib/router/index.js:317:13)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at /opt/mailtrain/server/node_modules/express/lib/router/index.js:284:7
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Function.process_params (/opt/mailtrain/server/node_modules/express/lib/router/index.js:335:12)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at next (/opt/mailtrain/server/node_modules/express/lib/router/index.js:275:10)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at app.use (/opt/mailtrain/server/app-builder.js:268:9)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at Layer.handle [as handle_request] (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:95:5)
Sep 10 17:35:10 server1 node[17899]: verb HTTP     at trim_prefix (/opt/mailtrain/server/node_modules/express/lib/router/index.js:317:13)
Sep 10 17:35:10 server1 node[17899]: verb HTTP   stack:
Sep 10 17:35:10 server1 node[17899]: verb HTTP    'Error: Invalid send configuration ID\n    at castToInteger (/opt/mailtrain/server/lib/helpers.js:39:15)\n    at rout$
Sep 10 17:35:10 server1 node[17899]: info HTTP #033[0mPOST /api/templates/5/send?access_token=182eca07b53c818849a6ebfb8a3f32ada78c7d2c #033[31m500 #033[0m12.237 ms - 51#033[0m

**Comment by pelkkala** [comment]
Turned out it's not actually the ID listed on the "send configurations" page but actually the int number you can see in the url while editing the send configuration.
