### ISSUE TITLE
V2 API - transactional email error: tx is not defined

### ISSUE THREAD

**Issue by mikpel123** [Mailtrain-org/mailtrain#700]
I'm trying to send out transactional email with API but I get the following error:

**ReferenceError: tx is not defined**

Here is a snippet from my syslog:
 
 
```Sep 10 18:40:56 server1 node[17899]: verb HTTP ReferenceError: tx is not defined
Sep 10 18:40:56 server1 node[17899]: verb HTTP ReferenceError: tx is not defined
Sep 10 18:40:56 server1 node[17899]: verb HTTP     at Object.queueAPITransactionalMessage (/opt/mailtrain/server/lib/message-sender.js:665:5)
Sep 10 18:40:56 server1 node[17899]: verb HTTP     at Object.sendAsTransactionalEmail (/opt/mailtrain/server/models/templates.js:171:29)
Sep 10 18:40:56 server1 node[17899]: verb HTTP  { ReferenceError: tx is not defined
Sep 10 18:40:56 server1 node[17899]: verb HTTP     at Object.queueAPITransactionalMessage (/opt/mailtrain/server/lib/message-sender.js:665:5)
Sep 10 18:40:56 server1 node[17899]: verb HTTP     at Object.sendAsTransactionalEmail (/opt/mailtrain/server/models/templates.js:171:29)
Sep 10 18:40:56 server1 node[17899]: verb HTTP   stack:
Sep 10 18:40:56 server1 node[17899]: verb HTTP    'ReferenceError: tx is not defined\n    at Object.queueAPITransactionalMessage (/opt/mailtrain/server/lib/message-sen$
Sep 10 18:40:56 server1 node[17899]: info HTTP #033[0mPOST /api/templates/5/send?access_token=****************************** #033[31m500 #033[0m16.412 ms - 39#033[0m ```

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
