### ISSUE TITLE
V2-docker : nodejs error "spawn ENOMEM" on new install with docker-compose

### ISSUE THREAD

**Issue by arnobase** [Mailtrain-org/mailtrain#704]
on debian 9.11
docker version 19.03.2
docker-compose version 1.24.1
haproxy configured for endpoints

git clone https://github.com/Mailtrain-org/mailtrain.git
git checkout development
MAILTRAIN_SETTINGS="--trustedUrlBase https://mailtrain.mydomain.fr --sandboxUrlBase https://sbox.mailtrain.mydomain.fr --publicUrlBase https://lists.mydomain.fr --withProxy" docker-compose up

and something went wrong in mailtrain image after "Importer process started" :

mailtrain_1  | info Importer Importer process started
mailtrain_1  | ERR! Error: spawn ENOMEM
mailtrain_1  | ERR!     at ChildProcess.spawn (internal/child_process.js:358:11)
mailtrain_1  | ERR!     at spawn (child_process.js:538:9)
mailtrain_1  | ERR!     at fork (child_process.js:113:10)
mailtrain_1  | ERR!     at fork (/app/server/lib/fork.js:25:19)
mailtrain_1  | ERR!     at Object.spawn (/app/server/lib/feedcheck.js:17:24)
mailtrain_1  | ERR!     at Object.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at Object.ret [as spawn] (eval at makeNodePromisifiedEval (/app/server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
mailtrain_1  | ERR!     at init (/app/server/index.js:114:21)
mailtrain_1  | ERR!     at process._tickCallback (internal/process/next_tick.js:68:7)
mailtrain_1  | ERR!  { Error: spawn ENOMEM
mailtrain_1  | ERR!     at ChildProcess.spawn (internal/child_process.js:358:11)
mailtrain_1  | ERR!     at spawn (child_process.js:538:9)
mailtrain_1  | ERR!     at fork (child_process.js:113:10)
mailtrain_1  | ERR!     at fork (/app/server/lib/fork.js:25:19)
mailtrain_1  | ERR!     at Object.spawn (/app/server/lib/feedcheck.js:17:24)
mailtrain_1  | ERR!     at Object.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at Object.ret [as spawn] (eval at makeNodePromisifiedEval (/app/server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
mailtrain_1  | ERR!     at init (/app/server/index.js:114:21)
mailtrain_1  | ERR!     at process._tickCallback (internal/process/next_tick.js:68:7)
mailtrain_1  | ERR!   stack:
mailtrain_1  | ERR!    'Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:358:11)\n    at spawn (child_process.js:538:9)\n    at fork (child_process.js:113:10)\n    at fork (/app/server/lib/fork.js:25:19)\n    at Object.spawn (/app/server/lib/feedcheck.js:17:24)\n    at Object.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Object.ret [as spawn] (eval at makeNodePromisifiedEval (/app/server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)\n    at init (/app/server/index.js:114:21)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
mailtrain_1  | ERR!   errno: 'ENOMEM',
mailtrain_1  | ERR!   code: 'ENOMEM',
mailtrain_1  | ERR!   syscall: 'spawn' }

I don't know if I missed something in the configuration of docker for memory usage ?

Thanks for your help
Arno

[full-error-mailtrain-docker.txt](https://github.com/Mailtrain-org/mailtrain/files/3605549/full-error-mailtrain-docker.txt)

**Comment by arnobase** [comment]
the issue is not reproduced on another machine, so I assume this was a specific problem on my setup
