### ISSUE TITLE
Make buttons to deploy to Heroku, ELB, Docker Store, etc

### ISSUE THREAD

**Issue by jaredpalmer** [Mailtrain-org/mailtrain#71]

**Comment by wesbos** [comment]
Have you done something like this before? Is it easy? 

Would be cool to have someone other than Andris do this so he can focus on the core dev.

**Comment by wesbos** [comment]
A digital ocean Droplet would be cool - I might try install it on there

**Comment by jaredpalmer** [comment]
@wesbos have not. would want it to be [Parse-Server's old deploy button cornucopia.](https://github.com/ParsePlatform/parse-server/blob/bd89338b39d384ab795ab39659b705be90ca7d2f/README.md). 

Will give it a shot.

**Comment by jaredpalmer** [comment]
@wesbos I'm not that familiar with .toml, but for Heroku we need to move to `.env` variables for configuration

**Comment by jaredpalmer** [comment]
@wesbos nvm I see that we can use a [.js module instead](https://github.com/andris9/mailtrain/blob/master/config/default.toml#L13). My b.

**Comment by jaredpalmer** [comment]
@wesbos @andris9 Got things almost working on Heroku with Jaws MariaDB. However, I am getting two errors (see below). I am able to login, but can't access the new automation tab.

```bash
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers Error: ER_BAD_FIELD_ERROR: Unknown column 'enabled' in 'where clause' 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:83:18) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:280:23) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:74:12) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at emitOne (events.js:90:13) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Socket.emit (events.js:182:7) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at readableAddChunk (_stream_readable.js:153:18) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Socket.Readable.push (_stream_readable.js:111:10) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     -------------------- 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:141:48) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at PoolConnection.query (/app/node_modules/mysql/lib/Connection.js:214:25) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at /app/services/triggers.js:27:20 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Ping.onOperationComplete [as _callback] (/app/node_modules/mysql/lib/Pool.js:108:5) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Ping.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Ping.Sequence.OkPacket (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:94:8) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:280:23) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:74:12) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28) 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers  { [Error: ER_BAD_FIELD_ERROR: Unknown column 'enabled' in 'where clause'] 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers   code: 'ER_BAD_FIELD_ERROR', 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers   errno: 1054, 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers   sqlState: '42S22', 
Jun 23 14:49:47 mailtrain2 app/web.1:  ERR! Triggers   index: 0 } 
```
and 

```bash
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail Error: ER_NO_SUCH_TABLE: Table 'mv2udkeh925uvsbb.queued' doesn't exist 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:83:18) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:280:23) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:74:12) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at emitOne (events.js:90:13) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Socket.emit (events.js:182:7) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at readableAddChunk (_stream_readable.js:153:18) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Socket.Readable.push (_stream_readable.js:111:10) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at TCP.onread (net.js:534:20) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     -------------------- 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:141:48) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at PoolConnection.query (/app/node_modules/mysql/lib/Connection.js:214:25) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at /app/services/sender.js:55:24 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Ping.onOperationComplete [as _callback] (/app/node_modules/mysql/lib/Pool.js:108:5) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Ping.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Ping.Sequence.OkPacket (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:94:8) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:280:23) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:74:12) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16) 
Jun 23 14:54:38 mailtrain2 app/web.1:  ERR! Mail     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail Error: ER_NO_SUCH_TABLE: Table 'mv2udkeh925uvsbb.queued' doesn't exist 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:83:18) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:280:23) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:74:12) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at emitOne (events.js:90:13) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Socket.emit (events.js:182:7) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at readableAddChunk (_stream_readable.js:153:18) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Socket.Readable.push (_stream_readable.js:111:10) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at TCP.onread (net.js:534:20) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     -------------------- 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:141:48) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at PoolConnection.query (/app/node_modules/mysql/lib/Connection.js:214:25) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at /app/services/sender.js:55:24 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Ping.onOperationComplete [as _callback] (/app/node_modules/mysql/lib/Pool.js:108:5) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Ping.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Ping.Sequence.OkPacket (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:94:8) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:280:23) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:74:12) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:39:16) 
Jun 23 14:54:43 mailtrain2 app/web.1:  ERR! Mail     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28) 
```

**Comment by andris9** [comment]
Sorry, this was a bug in sql setup files. Fixed in v1.12.1. Upgrade files were correct but the setup file for new installations was conflicting.

**Comment by jaredpalmer** [comment]
ok will submit a PR tomorrow for the Heroku Button.

**Comment by yochrepi** [comment]
Anything new with the heroku deploy? Would love to know how to do that.

**Comment by jaredpalmer** [comment]
After some research the config library can accept either toml or .js files.... Thus I created a [`production.js` file like so](https://github.com/andris9/mailtrain/compare/master...jaredpalmer:master#diff-824ed6e32de1ad360d5cf23b4b9f80ceR1). I also commented out the `Obj.keys` logic [here](https://github.com/andris9/mailtrain/compare/master...jaredpalmer:master#diff-6aac55bce60792c46bfc16ba0bed802bR15) so mailtrain could just use raw `.env` variables. However, this is really ugly, and I do not suggest doing it. Instead, just parse relevant `.env` variables inside of `production.js` and then keep the rest of mailtrain code as is. 

```javascript
// Better production.js
const url = require('url')

const redisUrl = url.parse(process.env.REDIS_URL)

module.exports = {
  ...
  redis:  {
     enabled: true,
     host: redisUrl.host,
     user: redisUrl.user,
    ... 
  },
 ....
}
```

**Other notes:**

If I recall correctly, l actually had to copy, paste, and then run the SQL initialization file on the JAWS DB instance after I connected to the db using Sequel Pro app. However, the first time I tried mailtrain on heroku (like 2 months ago), the db init ran smoothly. Not sure why. It may have had to do with getting setup right the first time vs. not.

**Comment by nebulade** [comment]
I am working on a Cloudron app for mailtrain and the package repository is at https://github.com/cloudron-io/mailtrain-app We also have such deploy/install buttons and I hope I can place it in the Readme as well at some point.

I was unable to find a svg or higher resolution of the mailtrain logo. Is such a version of the logo available somewhere? 

Thanks!

**Comment by andris9** [comment]
No, there is no high-res logo available. Mailtrain logo is from some random "create a logo online for $25" site and they only provided the current png file for that price.

**Comment by nebulade** [comment]
Ok, I quickly created an svg version, which I hope resembles roughly the pixel graphic logo. If you like you it, you can add that to the main repo. 

https://github.com/cloudron-io/mailtrain-app/blob/master/logo.svg

If rebuilding that logo is against some copyright of the "create a logo online" website, let me know, then I can delete it again.

**Comment by forgeOneHQ** [comment]
Closing, v1 is EOL. We can reopen and talk about it for v2.
