### ISSUE TITLE
V2: Campaign Statistics not updating

### ISSUE THREAD

**Issue by trantienthanh** [Mailtrain-org/mailtrain#716]
I'm running Mailtrain v2 with latest commit cbf2a6e39d3e40643c5e56f5867b7190079076ab.
I'm not quite sure the issue started from which commit but all my campaign statistics after August remain 0 (0%)
Blacklisted 0
Bounced 0 (0%)
Complaints 0 (0%)
Unsubscribed 0 (0%)
Opened 0 (0%)
Clicked 0 (0%)

No issue with sending emails. Success and bounced emails are all shown up in the log.
Any suggestion would be really appreciated.

**Comment by trantienthanh** [comment]
Bounced status still get updated correctly in the Subscribers list.

**Comment by trantienthanh** [comment]
verb HTTP Error: Not Found
verb HTTP     at Object.getTrackingSettingsByCidTx (/opt/mailtrain/server/models/campaigns.js:336:15)
verb HTTP  { Error: Not Found
verb HTTP     at Object.getTrackingSettingsByCidTx (/opt/mailtrain/server/models/campaigns.js:336:15)
verb HTTP   stack:
verb HTTP    'Error: Not Found\n    at Object.getTrackingSettingsByCidTx (/opt/mailtrain/server/models/campaigns.js:336:15)',
verb HTTP   type: 'NotFoundError',
verb HTTP   data: undefined,
verb HTTP   status: 404 }
Error [ERR_HTTP_HEADERS_SENT]: /opt/mailtrain/server/views/layout.hbs: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/opt/mailtrain/server/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/opt/mailtrain/server/node_modules/express/lib/response.js:170:12)
    at done (/opt/mailtrain/server/node_modules/express/lib/response.js:1008:10)
    at /opt/mailtrain/server/node_modules/hbs/lib/hbs.js:106:11
    at Object.done (/opt/mailtrain/server/node_modules/hbs/lib/async.js:74:20)
    at /opt/mailtrain/server/node_modules/hbs/lib/hbs.js:101:20
    at /opt/mailtrain/server/node_modules/hbs/lib/hbs.js:56:11
    at Object.done (/opt/mailtrain/server/node_modules/hbs/lib/async.js:74:20)
    at render_file (/opt/mailtrain/server/node_modules/hbs/lib/hbs.js:51:20)
    at render_with_layout (/opt/mailtrain/server/node_modules/hbs/lib/hbs.js:92:5)
    at Instance.middleware (/opt/mailtrain/server/node_modules/hbs/lib/hbs.js:145:14)
    at View.render (/opt/mailtrain/server/node_modules/express/lib/view.js:135:8)
    at tryRender (/opt/mailtrain/server/node_modules/express/lib/application.js:640:10)
    at Function.render (/opt/mailtrain/server/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/opt/mailtrain/server/node_modules/express/lib/response.js:1012:7)
    at app.use (/opt/mailtrain/server/app-builder.js:374:21)
    at Layer.handle_error (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/mailtrain/server/node_modules/express/lib/router/index.js:315:13)
    at /opt/mailtrain/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/mailtrain/server/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/mailtrain/server/node_modules/express/lib/router/index.js:275:10)

**Comment by forgeOneHQ** [comment]
@trantienthanh please pull the latest version of v2 and try again. You are welcome to open a new issue and we will help you to investigate if you provide us all infos how you deployed it, confguration and log informations.
