### ISSUE TITLE
V2: Error generating report 

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#725]
Hello,

I'm currently testing v2 in a staging environment and all of the mailing functionality works, however when trying to generate a report I'm getting an odd error:

```
WARNING: NODE_ENV value of 'staging' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
{ Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    --------------------
    at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/app/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/app/server/node_modules/mysql/lib/Connection.js:119:18)
    at _bluebird.default (/app/server/node_modules/knex/lib/dialects/mysql/index.js:82:18)
    at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/app/server/node_modules/knex/lib/dialects/mysql/index.js:77:12)
    at create (/app/server/node_modules/knex/lib/client.js:282:21)
    at utils_1.tryPromise (/app/server/node_modules/tarn/lib/Pool.js:315:34)
    at Object.tryPromise (/app/server/node_modules/tarn/lib/utils.js:53:24)
    at Promise (/app/server/node_modules/tarn/lib/Pool.js:315:17)
    at new Promise (<anonymous>)
    at callbackOrPromise (/app/server/node_modules/tarn/lib/Pool.js:306:12)
    at Pool._create (/app/server/node_modules/tarn/lib/Pool.js:236:9)
    at Pool._doCreate (/app/server/node_modules/tarn/lib/Pool.js:208:36)
    at Pool._tryAcquireOrCreate (/app/server/node_modules/tarn/lib/Pool.js:159:18)
    at Pool.acquire (/app/server/node_modules/tarn/lib/Pool.js:85:14)
    at _bluebird.default.try (/app/server/node_modules/knex/lib/client.js:333:50)
    at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
    at Client_MySQL.acquireConnection (/app/server/node_modules/knex/lib/client.js:333:33)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true }
```

I'm not sure why this is happening...I have a `server/config/staging.yml` file with the correct mysql information to my database (it's working for everything else) but for some reason the reporting side doesn't seem to be using the same config. 

Any insights here?

**Comment by ericuldall** [comment]
*Bump*

Any update here ?

**Comment by chiacy** [comment]
Bump

**Comment by ericuldall** [comment]
@bures Could I get your input on this?

**Comment by ericuldall** [comment]
Would really like to see if we can get these reports working, however it seems like the child process is looking in the wrong directory for the config folder. @bures or anyone else have a fix on this?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
