### ISSUE TITLE
V2: Reporting template error in 'Aggregate open counts'

### ISSUE THREAD

**Issue by Pistus** [Mailtrain-org/mailtrain#730]
I am looking into the reporting section and face an issue with the generated sql/knex queries. I am trying to run the "Aggregate open count" template as a report on a list that has Country as a custom field but get this error:

```
{ Error: ER_DERIVED_MUST_HAVE_ALIAS: Every derived table must have its own alias
    at Query.Sequence._packetToError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:201:25)
    at /opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
    at Promise._execute (/opt/mailtrain/server/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
    at Client_MySQL.query (/opt/mailtrain/server/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/opt/mailtrain/server/node_modules/knex/lib/runner.js:138:36)
    at Runner.tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:15:34)
    at /opt/mailtrain/server/node_modules/knex/lib/runner.js:47:21
    at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:643:18)
    at PromiseArray._resolve (/opt/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/opt/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:144:14)
  code: 'ER_DERIVED_MUST_HAVE_ALIAS',
  errno: 1248,
  sqlMessage: 'Every derived table must have its own alias',
  sqlState: '42000',
  index: 0,
  sql:
   'select count(*) as `count_all`, SUM(IF(`tracker:count` IS NULL, 0, 1)) AS count_opened from (select *) group by `field:country`' }
```

The problem seems to be with the from clause `from (select *)` which needs an alias or changed to use a table. And this seems to stem from here [server/models/reports.js](https://github.com/Mailtrain-org/mailtrain/blob/development/server/models/reports.js#L363) - but I havent wrapped my head around how that generates `(select *)`

**Comment by Neseek77** [comment]
@bures Would you mind explaining or guiding us through?
Facing the same problem.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
