### ISSUE TITLE
Mailtrain v2 - Update issue

### ISSUE THREAD

**Issue by talheim-it** [Mailtrain-org/mailtrain#814]
I tried to update it as written in the other ticket:
Now I am having an issue:
info Using local auth 
ERR! Error: Could not connect to the database. Check MySQL host and port configuration
ERR!     at db.getConnection (/opt/mailtrain/server/lib/dbcheck.js:30:23)
ERR!     at Handshake.onConnect (/opt/mailtrain/server/node_modules/mysql/lib/Pool.js:58:9)
ERR!     at Handshake.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
ERR!     at Handshake._callback (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:491:16)
ERR!     at Handshake.Sequence.end (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
ERR!     at Protocol.handleNetworkError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:369:14)
ERR!     at PoolConnection.Connection._handleNetworkError (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:421:18)
ERR!     at Socket.emit (events.js:198:13)
ERR!     at Socket.EventEmitter.emit (domain.js:448:20)
ERR!     at emitErrorNT (internal/streams/destroy.js:91:8)
ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
ERR!     at process._tickCallback (internal/process/next_tick.js:63:19)
ERR!  { Error: Could not connect to the database. Check MySQL host and port configuration
ERR!     at db.getConnection (/opt/mailtrain/server/lib/dbcheck.js:30:23)
ERR!     at Handshake.onConnect (/opt/mailtrain/server/node_modules/mysql/lib/Pool.js:58:9)
ERR!     at Handshake.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
ERR!     at Handshake._callback (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:491:16)
ERR!     at Handshake.Sequence.end (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
ERR!     at Protocol.handleNetworkError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:369:14)
ERR!     at PoolConnection.Connection._handleNetworkError (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:421:18)
ERR!     at Socket.emit (events.js:198:13)
ERR!     at Socket.EventEmitter.emit (domain.js:448:20)
ERR!     at emitErrorNT (internal/streams/destroy.js:91:8)
ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
ERR!     at process._tickCallback (internal/process/next_tick.js:63:19)
ERR!   cause:
ERR!    Error: Could not connect to the database. Check MySQL host and port configuration
ERR!        at db.getConnection (/opt/mailtrain/server/lib/dbcheck.js:30:23)
ERR!        at Handshake.onConnect (/opt/mailtrain/server/node_modules/mysql/lib/Pool.js:58:9)
ERR!        at Handshake.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
ERR!        at Handshake._callback (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:491:16)
ERR!        at Handshake.Sequence.end (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
ERR!        at Protocol.handleNetworkError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:369:14)
ERR!        at PoolConnection.Connection._handleNetworkError (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:421:18)
ERR!        at Socket.emit (events.js:198:13)
ERR!        at Socket.EventEmitter.emit (domain.js:448:20)
ERR!        at emitErrorNT (internal/streams/destroy.js:91:8)
ERR!        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
ERR!        at process._tickCallback (internal/process/next_tick.js:63:19),
ERR!   isOperational: true,
ERR!   stack:
ERR!    'Error: Could not connect to the database. Check MySQL host and port configuration\n    at db.getConnection (/opt/mailtrain/server/lib/dbcheck.js:30:23)\n    at Handshake.onConnect (/opt/mailtrain/server/node_modules/mysql/lib/Pool.js:58:9)\n    at Handshake.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)\n    at Handshake._callback (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:491:16)\n    at Handshake.Sequence.end (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)\n    at Protocol.handleNetworkError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:369:14)\n    at PoolConnection.Connection._handleNetworkError (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:421:18)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' }

NPM was upgraded

I went through each folder with package.json file for installing/upgrading.

Credentials are correct in production.yml .

**Comment by talheim-it** [comment]
Fixed, another issue is occuring now. Closing.
