### ISSUE TITLE
[v2] Fresh install - got: Error: Packets out of order.

### ISSUE THREAD

**Issue by atomtigerzoo** [Mailtrain-org/mailtrain#920]
A fresh install with the default _docker-compose.yml_ of the v2 docker version fails to run with the following logs:

```
Creating mailtrain_redis_1     ... done
Creating mailtrain_mongo_1     ... done
Creating mailtrain_mailtrain_1 ... done
Creating mailtrain_mysql_1     ... done
Attaching to mailtrain_redis_1, mailtrain_mailtrain_1, mailtrain_mysql_1, mailtrain_mongo_1
mailtrain_1  | Info: Generating application/production.yaml
mailtrain_1  | Info: LDAP not enabled
mailtrain_1  | Info: Generating server/production.yaml
mailtrain_1  | Info: Waiting for MySQL Server
mysql_1      | 2020-07-26 17:59:55+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.13+maria~focal started.
mysql_1      | 2020-07-26 17:59:55+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1      | 2020-07-26 17:59:55+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.4.13+maria~focal started.
redis_1      | 1:C 26 Jul 2020 17:59:54.286 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1      | 1:C 26 Jul 2020 17:59:54.286 # Redis version=5.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1      | 1:C 26 Jul 2020 17:59:54.286 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1      | 1:M 26 Jul 2020 17:59:54.287 * Running mode=standalone, port=6379.
redis_1      | 1:M 26 Jul 2020 17:59:54.287 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1      | 1:M 26 Jul 2020 17:59:54.287 # Server initialized
redis_1      | 1:M 26 Jul 2020 17:59:54.287 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | 1:M 26 Jul 2020 17:59:54.287 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1      | 1:M 26 Jul 2020 17:59:54.288 * DB loaded from disk: 0.000 seconds
redis_1      | 1:M 26 Jul 2020 17:59:54.288 * Ready to accept connections
mongo_1      | 2020-07-26T17:59:55.630+0000 I STORAGE  [main] Max cache overflow file size custom option: 0
mongo_1      | 2020-07-26T17:59:55.635+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1      | 2020-07-26T17:59:55.642+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=344e3f77a12e
mongo_1      | 2020-07-26T17:59:55.642+0000 I CONTROL  [initandlisten] db version v4.0.12
mongo_1      | 2020-07-26T17:59:55.642+0000 I CONTROL  [initandlisten] git version: 5776e3cbf9e7afe86e6b29e22520ffb6766e95d4
mongo_1      | 2020-07-26T17:59:55.642+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo_1      | 2020-07-26T17:59:55.642+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1      | 2020-07-26T17:59:55.643+0000 I CONTROL  [initandlisten] modules: none
mongo_1      | 2020-07-26T17:59:55.643+0000 I CONTROL  [initandlisten] build environment:
mongo_1      | 2020-07-26T17:59:55.643+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo_1      | 2020-07-26T17:59:55.643+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1      | 2020-07-26T17:59:55.643+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1      | 2020-07-26T17:59:55.644+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
mongo_1      | 2020-07-26T17:59:55.645+0000 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo_1      | 2020-07-26T17:59:55.645+0000 I STORAGE  [initandlisten]
mongo_1      | 2020-07-26T17:59:55.645+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1      | 2020-07-26T17:59:55.646+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1      | 2020-07-26T17:59:55.646+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=508M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mysql_1      | 2020-07-26 17:59:56 0 [Note] mysqld (mysqld 10.4.13-MariaDB-1:10.4.13+maria~focal) starting as process 1 ...
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Using Linux native AIO
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Uses event mutexes
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Number of pools: 1
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Using SSE2 crc32 instructions
mysql_1      | 2020-07-26 17:59:56 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Waiting for purge to start
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: 10.4.13 started; log sequence number 61026; transaction id 21
mysql_1      | 2020-07-26 17:59:56 0 [Note] Plugin 'FEEDBACK' is disabled.
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1      | 2020-07-26 17:59:56 0 [Note] Server socket created on IP: '::'.
mysql_1      | 2020-07-26 17:59:56 0 [Note] InnoDB: Buffer pool(s) load completed at 200726 17:59:56
mysql_1      | 2020-07-26 17:59:56 0 [Warning] 'user' entry 'root@184e30056aac' ignored in --skip-name-resolve mode.
mysql_1      | 2020-07-26 17:59:56 0 [Warning] 'user' entry '@184e30056aac' ignored in --skip-name-resolve mode.
mysql_1      | 2020-07-26 17:59:56 0 [Warning] 'proxies_priv' entry '@% root@184e30056aac' ignored in --skip-name-resolve mode.
mysql_1      | 2020-07-26 17:59:56 0 [Note] Reading of all Master_info entries succeeded
mysql_1      | 2020-07-26 17:59:56 0 [Note] Added new Master_info '' to hash table
mysql_1      | 2020-07-26 17:59:56 0 [Note] mysqld: ready for connections.
mysql_1      | Version: '10.4.13-MariaDB-1:10.4.13+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mongo_1      | 2020-07-26T17:59:56.568+0000 I STORAGE  [initandlisten] WiredTiger message [1595786396:568199][1:0x7f497f2f3a80], txn-recover: Main recovery loop: starting at 4/4864 to 5/256
mongo_1      | 2020-07-26T17:59:56.627+0000 I STORAGE  [initandlisten] WiredTiger message [1595786396:627358][1:0x7f497f2f3a80], txn-recover: Recovering log 4 through 5
mongo_1      | 2020-07-26T17:59:56.713+0000 I STORAGE  [initandlisten] WiredTiger message [1595786396:713172][1:0x7f497f2f3a80], txn-recover: Recovering log 5 through 5
mongo_1      | 2020-07-26T17:59:56.747+0000 I STORAGE  [initandlisten] WiredTiger message [1595786396:747129][1:0x7f497f2f3a80], txn-recover: Set global recovery timestamp: 0
mysql_1      | 2020-07-26 17:59:56 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '172.18.0.3' (This connection closed normally without authentication)
mailtrain_1  | Info: Waiting for Redis Server
mailtrain_1  | Info: Waiting for MongoDB Server
mongo_1      | 2020-07-26T17:59:56.984+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo_1      | 2020-07-26T17:59:57.100+0000 I CONTROL  [initandlisten]
mongo_1      | 2020-07-26T17:59:57.101+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1      | 2020-07-26T17:59:57.101+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1      | 2020-07-26T17:59:57.102+0000 I CONTROL  [initandlisten]
mongo_1      | 2020-07-26T17:59:57.103+0000 I CONTROL  [initandlisten]
mongo_1      | 2020-07-26T17:59:57.104+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
mongo_1      | 2020-07-26T17:59:57.105+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongo_1      | 2020-07-26T17:59:57.105+0000 I CONTROL  [initandlisten]
mongo_1      | 2020-07-26T17:59:57.117+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1      | 2020-07-26T17:59:57.119+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mongo_1      | 2020-07-26T17:59:57.812+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:33688 #1 (1 connection now open)
mongo_1      | 2020-07-26T17:59:57.813+0000 I NETWORK  [conn1] end connection 172.18.0.3:33688 (0 connections now open)
mailtrain_1  | info Using local auth
mysql_1      | 2020-07-26 18:00:00 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.18.0.3' (This connection closed normally without authentication)
mailtrain_1  | ERR! Error: Packets out of order. Got: 1 Expected: 0
mailtrain_1  | ERR!     at Parser._tryReadPacketHeader (/app/server/node_modules/mysql/lib/protocol/Parser.js:470:15)
mailtrain_1  | ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:33:29)
mailtrain_1  | ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
mailtrain_1  | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
mailtrain_1  | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
mailtrain_1  | ERR!     at Socket.emit (events.js:198:13)
mailtrain_1  | ERR!     at Socket.EventEmitter.emit (domain.js:448:20)
mailtrain_1  | ERR!     at addChunk (_stream_readable.js:288:12)
mailtrain_1  | ERR!     at readableAddChunk (_stream_readable.js:269:11)
mailtrain_1  | ERR!     at Socket.Readable.push (_stream_readable.js:224:10)
mailtrain_1  | ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
mailtrain_1  | ERR!     --------------------
mailtrain_1  | ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mailtrain_1  | ERR!     at Protocol.handshake (/app/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)
mailtrain_1  | ERR!     at PoolConnection.connect (/app/server/node_modules/mysql/lib/Connection.js:119:18)
mailtrain_1  | ERR!     at Pool.getConnection (/app/server/node_modules/mysql/lib/Pool.js:48:16)
mailtrain_1  | ERR!     at listTables (/app/server/lib/dbcheck.js:24:8)
mailtrain_1  | ERR!     at runUpdates (/app/server/lib/dbcheck.js:164:5)
mailtrain_1  | ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at ret (eval at makeNodePromisifiedEval (/app/server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
mailtrain_1  | ERR!     at dbcheck (/app/server/lib/dbcheck.js:226:11)
mailtrain_1  | ERR!     at init (/app/server/index.js:82:11)
mailtrain_1  | ERR!     at Object.<anonymous> (/app/server/index.js:128:1)
mailtrain_1  | ERR!     at Module._compile (internal/modules/cjs/loader.js:778:30)
mailtrain_1  | ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
mailtrain_1  | ERR!     at Module.load (internal/modules/cjs/loader.js:653:32)
mailtrain_1  | ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
mailtrain_1  | ERR!     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
mailtrain_1  | ERR!     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
mailtrain_1  | ERR!     at startup (internal/bootstrap/node.js:283:19)
mailtrain_1  | ERR!     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
mailtrain_1  | ERR!  { Error: Packets out of order. Got: 1 Expected: 0
mailtrain_1  | ERR!     at Parser._tryReadPacketHeader (/app/server/node_modules/mysql/lib/protocol/Parser.js:470:15)
mailtrain_1  | ERR!     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:33:29)
mailtrain_1  | ERR!     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
mailtrain_1  | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
mailtrain_1  | ERR!     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
mailtrain_1  | ERR!     at Socket.emit (events.js:198:13)
mailtrain_1  | ERR!     at Socket.EventEmitter.emit (domain.js:448:20)
mailtrain_1  | ERR!     at addChunk (_stream_readable.js:288:12)
mailtrain_1  | ERR!     at readableAddChunk (_stream_readable.js:269:11)
mailtrain_1  | ERR!     at Socket.Readable.push (_stream_readable.js:224:10)
mailtrain_1  | ERR!     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
mailtrain_1  | ERR!     --------------------
mailtrain_1  | ERR!     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mailtrain_1  | ERR!     at Protocol.handshake (/app/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)
mailtrain_1  | ERR!     at PoolConnection.connect (/app/server/node_modules/mysql/lib/Connection.js:119:18)
mailtrain_1  | ERR!     at Pool.getConnection (/app/server/node_modules/mysql/lib/Pool.js:48:16)
mailtrain_1  | ERR!     at listTables (/app/server/lib/dbcheck.js:24:8)
mailtrain_1  | ERR!     at runUpdates (/app/server/lib/dbcheck.js:164:5)
mailtrain_1  | ERR!     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at ret (eval at makeNodePromisifiedEval (/app/server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
mailtrain_1  | ERR!     at dbcheck (/app/server/lib/dbcheck.js:226:11)
mailtrain_1  | ERR!     at init (/app/server/index.js:82:11)
mailtrain_1  | ERR!     at Object.<anonymous> (/app/server/index.js:128:1)
mailtrain_1  | ERR!     at Module._compile (internal/modules/cjs/loader.js:778:30)
mailtrain_1  | ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
mailtrain_1  | ERR!     at Module.load (internal/modules/cjs/loader.js:653:32)
mailtrain_1  | ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
mailtrain_1  | ERR!     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
mailtrain_1  | ERR!     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
mailtrain_1  | ERR!     at startup (internal/bootstrap/node.js:283:19)
mailtrain_1  | ERR!     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
mailtrain_1  | ERR!   cause:
mailtrain_1  | ERR!    { Error: Packets out of order. Got: 1 Expected: 0
mailtrain_1  | ERR!        at Parser._tryReadPacketHeader (/app/server/node_modules/mysql/lib/protocol/Parser.js:470:15)
mailtrain_1  | ERR!        at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:33:29)
mailtrain_1  | ERR!        at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
mailtrain_1  | ERR!        at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
mailtrain_1  | ERR!        at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
mailtrain_1  | ERR!        at Socket.emit (events.js:198:13)
mailtrain_1  | ERR!        at Socket.EventEmitter.emit (domain.js:448:20)
mailtrain_1  | ERR!        at addChunk (_stream_readable.js:288:12)
mailtrain_1  | ERR!        at readableAddChunk (_stream_readable.js:269:11)
mailtrain_1  | ERR!        at Socket.Readable.push (_stream_readable.js:224:10)
mailtrain_1  | ERR!        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
mailtrain_1  | ERR!        --------------------
mailtrain_1  | ERR!        at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mailtrain_1  | ERR!        at Protocol.handshake (/app/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)
mailtrain_1  | ERR!        at PoolConnection.connect (/app/server/node_modules/mysql/lib/Connection.js:119:18)
mailtrain_1  | ERR!        at Pool.getConnection (/app/server/node_modules/mysql/lib/Pool.js:48:16)
mailtrain_1  | ERR!        at listTables (/app/server/lib/dbcheck.js:24:8)
mailtrain_1  | ERR!        at runUpdates (/app/server/lib/dbcheck.js:164:5)
mailtrain_1  | ERR!        at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!        at ret (eval at makeNodePromisifiedEval (/app/server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
mailtrain_1  | ERR!        at dbcheck (/app/server/lib/dbcheck.js:226:11)
mailtrain_1  | ERR!        at init (/app/server/index.js:82:11)
mailtrain_1  | ERR!        at Object.<anonymous> (/app/server/index.js:128:1)
mailtrain_1  | ERR!        at Module._compile (internal/modules/cjs/loader.js:778:30)
mailtrain_1  | ERR!        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
mailtrain_1  | ERR!        at Module.load (internal/modules/cjs/loader.js:653:32)
mailtrain_1  | ERR!        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
mailtrain_1  | ERR!        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
mailtrain_1  | ERR!        at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
mailtrain_1  | ERR!        at startup (internal/bootstrap/node.js:283:19)
mailtrain_1  | ERR!        at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3) code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true },
mailtrain_1  | ERR!   isOperational: true,
mailtrain_1  | ERR!   stack:
mailtrain_1  | ERR!    'Error: Packets out of order. Got: 1 Expected: 0\n    at Parser._tryReadPacketHeader (/app/server/node_modules/mysql/lib/protocol/Parser.js:470:15)\n    at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:33:29)\n    at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n    --------------------\n    at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at Protocol.handshake (/app/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)\n    at PoolConnection.connect (/app/server/node_modules/mysql/lib/Connection.js:119:18)\n    at Pool.getConnection (/app/server/node_modules/mysql/lib/Pool.js:48:16)\n    at listTables (/app/server/lib/dbcheck.js:24:8)\n    at runUpdates (/app/server/lib/dbcheck.js:164:5)\n    at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at ret (eval at makeNodePromisifiedEval (/app/server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)\n    at dbcheck (/app/server/lib/dbcheck.js:226:11)\n    at init (/app/server/index.js:82:11)\n    at Object.<anonymous> (/app/server/index.js:128:1)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)',
mailtrain_1  | ERR!   code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
mailtrain_1  | ERR!   fatal: true }
mailtrain_mailtrain_1 exited with code 1
```

Any ideas what I did wrong or how to fix this?

**Comment by atomtigerzoo** [comment]
Deleted all containers, different problem now ;) Closing this.
