### ISSUE TITLE
(v2) Plain text rendering of Mosaico template issue

### ISSUE THREAD

**Issue by elitzer2** [Mailtrain-org/mailtrain#943]
Not sure if I've set something up incorrectly, but when I try to view the plain text of the email using the "To extract the text from HTML click here" link, I get the following stack dump. I am running on `Red Hat Enterprise Linux release 8.2` with `premailer-api@1.0.4` on an EC2 instance and ran the CentOS 8 install script to get things going following [these](https://github.com/Mailtrain-org/mailtrain/tree/development#installation-on-fresh-centos-7-or-ubuntu-1804-lts-public-website-secured-by-ssl) instructions. I noticed the `mvis` client/server folders don't have a `package-lock.json` defined so not sure if it would be due to any differences in versions in there.

There are the template settings used in the campaign:
<img width="491" alt="Screen Shot 2020-08-27 at 7 38 04 PM" src="https://user-images.githubusercontent.com/5624305/91508361-f3243500-e89c-11ea-9df7-6f939f3d4c79.png">

I also just tested this in a local docker container and it seems to be broken there as well.

```
node[4763]: verb HTTP SyntaxError: Unexpected token < in JSON at position 0
node[4763]: verb HTTP     at JSON.parse (<anonymous>)
node[4763]: verb HTTP     at Request.handlePremailerResponse [as _callback] (/opt/mailtrain/server/node_modules/premailer-api/premailer.js:103:23)
node[4763]: verb HTTP     at Request.self.callback (/opt/mailtrain/server/node_modules/request/request.js:185:22)
node[4763]: verb HTTP     at Request.emit (events.js:198:13)
node[4763]: verb HTTP     at Request.EventEmitter.emit (domain.js:448:20)
node[4763]: verb HTTP     at Request.<anonymous> (/opt/mailtrain/server/node_modules/request/request.js:1161:10)
node[4763]: verb HTTP     at Request.emit (events.js:198:13)
node[4763]: verb HTTP     at Request.EventEmitter.emit (domain.js:448:20)
node[4763]: verb HTTP     at IncomingMessage.<anonymous> (/opt/mailtrain/server/node_modules/request/request.js:1083:12)
node[4763]: verb HTTP     at Object.onceWrapper (events.js:286:20)
node[4763]: verb HTTP     at IncomingMessage.emit (events.js:203:15)
node[4763]: verb HTTP     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
node[4763]: verb HTTP     at endReadableNT (_stream_readable.js:1145:12)
node[4763]: verb HTTP     at process._tickCallback (internal/process/next_tick.js:63:19)
node[4763]: verb HTTP  { SyntaxError: Unexpected token < in JSON at position 0
node[4763]: verb HTTP     at JSON.parse (<anonymous>)
node[4763]: verb HTTP     at Request.handlePremailerResponse [as _callback] (/opt/mailtrain/server/node_modules/premailer-api/premailer.js:103:23)
node[4763]: verb HTTP     at Request.self.callback (/opt/mailtrain/server/node_modules/request/request.js:185:22)
node[4763]: verb HTTP     at Request.emit (events.js:198:13)
node[4763]: verb HTTP     at Request.EventEmitter.emit (domain.js:448:20)
node[4763]: verb HTTP     at Request.<anonymous> (/opt/mailtrain/server/node_modules/request/request.js:1161:10)
node[4763]: verb HTTP     at Request.emit (events.js:198:13)
node[4763]: verb HTTP     at Request.EventEmitter.emit (domain.js:448:20)
node[4763]: verb HTTP     at IncomingMessage.<anonymous> (/opt/mailtrain/server/node_modules/request/request.js:1083:12)
node[4763]: verb HTTP     at Object.onceWrapper (events.js:286:20)
node[4763]: verb HTTP     at IncomingMessage.emit (events.js:203:15)
node[4763]: verb HTTP     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
node[4763]: verb HTTP     at endReadableNT (_stream_readable.js:1145:12)
node[4763]: verb HTTP     at process._tickCallback (internal/process/next_tick.js:63:19)
node[4763]: verb HTTP   stack:
node[4763]: verb HTTP    'SyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at Request.handlePremailerResponse [as _callback] (/opt/mailtrain/server/node_modules/premailer-api/premailer.js:103:23)\n    at Request.self.callback (/opt/mailtrain/server/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:198:13)\n    at Request.EventEmitter.emit (domain.js:448:20)\n    at Request.<anonymous> (/opt/mailtrain/server/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:198:13)\n    at Request.EventEmitter.emit (domain.js:448:20)\n    at IncomingMessage.<anonymous> (/opt/mailtrain/server/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:286:20)\n    at IncomingMessage.emit (events.js:203:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:448:20)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' }
```

**Comment by elitzer2** [comment]
Looks like the premailer API is no longer running: http://premailer.dialect.ca/
You have to host the code yourself and can specify a local URL possibly.
